Repository UnityTechnologies/open-project-1, pull requests merged in 2020-11, with the labels that each got.

#124 Allow switching from the Idle state to Sliding or JumpDescending
  UOP1_Project/Assets/ScriptableObjects/Protagonist/States/Idle.asset
Labels: bug (important)

#137 Water shader v1
  UOP1_Project/Assets/Scenes/ArtShowcase.unity
  UOP1_Project/Assets/Shaders/ToonWater.meta
  UOP1_Project/Assets/Shaders/ToonWater/CartoonWater.mat
  UOP1_Project/Assets/Shaders/ToonWater/CartoonWater.mat.meta
  UOP1_Project/Assets/Shaders/ToonWater/CartoonWater.shadergraph
  UOP1_Project/Assets/Shaders/ToonWater/CartoonWater.shadergraph.meta
Labels: art

#117 Generic (Scriptable) Object Pool
  UOP1_Project/Assets/LocalPoolTester.cs
  UOP1_Project/Assets/LocalPoolTester.cs.meta
  UOP1_Project/Assets/Scripts/Factory.meta
  UOP1_Project/Assets/Scripts/Factory/ComponentFactorySO.cs
  UOP1_Project/Assets/Scripts/Factory/ComponentFactorySO.cs.meta
  UOP1_Project/Assets/Scripts/Factory/FactorySO.cs
  UOP1_Project/Assets/Scripts/Factory/FactorySO.cs.meta
  UOP1_Project/Assets/Scripts/Factory/IFactory.cs
  UOP1_Project/Assets/Scripts/Factory/IFactory.cs.meta
  UOP1_Project/Assets/Scripts/Pool.meta
  UOP1_Project/Assets/Scripts/Pool/ComponentPool.cs
  UOP1_Project/Assets/Scripts/Pool/ComponentPool.cs.meta
  UOP1_Project/Assets/Scripts/Pool/Example.meta
  UOP1_Project/Assets/Scripts/Pool/Example/Assets.meta
  UOP1_Project/Assets/Scripts/Pool/Example/Assets/Example.unity
  UOP1_Project/Assets/Scripts/Pool/Example/Assets/Example.unity.meta
  UOP1_Project/Assets/Scripts/Pool/Example/Assets/ParticleFactory.asset
  UOP1_Project/Assets/Scripts/Pool/Example/Assets/ParticleFactory.asset.meta
  UOP1_Project/Assets/Scripts/Pool/Example/Assets/Particles.prefab
  UOP1_Project/Assets/Scripts/Pool/Example/Assets/Particles.prefab.meta
  UOP1_Project/Assets/Scripts/Pool/Example/Assets/Shared GlobalParticlePool.asset
  UOP1_Project/Assets/Scripts/Pool/Example/Assets/Shared GlobalParticlePool.asset.meta
  UOP1_Project/Assets/Scripts/Pool/Example/ParticleFactorySO.cs
  UOP1_Project/Assets/Scripts/Pool/Example/ParticleFactorySO.cs.meta
  UOP1_Project/Assets/Scripts/Pool/Example/ParticlePoolSO.cs
  UOP1_Project/Assets/Scripts/Pool/Example/ParticlePoolSO.cs.meta
  UOP1_Project/Assets/Scripts/Pool/Example/PoolTester.cs
  UOP1_Project/Assets/Scripts/Pool/Example/PoolTester.cs.meta
  UOP1_Project/Assets/Scripts/Pool/Example/PoolableParticle.cs
  UOP1_Project/Assets/Scripts/Pool/Example/PoolableParticle.cs.meta
  UOP1_Project/Assets/Scripts/Pool/IPool.cs
  UOP1_Project/Assets/Scripts/Pool/IPool.cs.meta
  UOP1_Project/Assets/Scripts/Pool/IPoolable.cs
  UOP1_Project/Assets/Scripts/Pool/IPoolable.cs.meta
  UOP1_Project/Assets/Scripts/Pool/PoolSO.cs
  UOP1_Project/Assets/Scripts/Pool/PoolSO.cs.meta
Labels: enhancement

#141 Input checks from Phase.Started => Phase.Performed
  UOP1_Project/Assets/Scripts/Input/InputReader.cs
Labels: enhancement

#138 Spawn location editor
  UOP1_Project/Assets/Prefabs/GameplayEssentials/SpawnSystem.prefab
  UOP1_Project/Assets/Scripts/ClickToPlaceHelper.cs
  UOP1_Project/Assets/Scripts/ClickToPlaceHelper.cs.meta
  UOP1_Project/Assets/Scripts/Editor/SpawnLocationEditor.cs
  UOP1_Project/Assets/Scripts/Editor/SpawnLocationEditor.cs.meta
Labels: editor tool

#146 Simple mouse based camera controls
  UOP1_Project/Assets/Prefabs/GameplayEssentials/CameraSystem.prefab
  UOP1_Project/Assets/Scripts/CameraManager.cs
  UOP1_Project/Assets/Scripts/Input/GameInput.cs
  UOP1_Project/Assets/Scripts/Input/InputReader.cs
  UOP1_Project/Assets/Settings/Input/GameInput.inputactions
Labels: enhancement

#147 Pool Cleanup
  UOP1_Project/Assets/Scripts/Pool/ComponentPoolSO.cs
  UOP1_Project/Assets/Scripts/Pool/ComponentPoolSO.cs.meta
  UOP1_Project/Assets/Scripts/Pool/Example/Assets/SharedGlobalParticlePool.asset
  UOP1_Project/Assets/Scripts/Pool/Example/Assets/SharedGlobalParticlePool.asset.meta
  UOP1_Project/Assets/Scripts/Pool/Example/LocalPoolTester.cs
  UOP1_Project/Assets/Scripts/Pool/Example/LocalPoolTester.cs.meta
  UOP1_Project/Assets/Scripts/Pool/Example/ParticlePoolSO.cs
Labels: enhancement

#135 Working dialogue and cutscene system.
  .editorconfig
  UOP1_Project/Assets/Cutscenes.meta
  UOP1_Project/Assets/Cutscenes/ExampleCutscene.playable
  UOP1_Project/Assets/Cutscenes/ExampleCutscene.playable.meta
  UOP1_Project/Assets/Materials/Obstacles_Blue.mat
  UOP1_Project/Assets/Prefabs/GameplayEssentials/CameraSystem.prefab
  UOP1_Project/Assets/Scenes/Examples.meta
  UOP1_Project/Assets/Scenes/Examples/CutsceneExample.unity
  UOP1_Project/Assets/Scenes/Examples/CutsceneExample.unity.meta
  UOP1_Project/Assets/ScriptableObjects/Narrative.meta
  UOP1_Project/Assets/ScriptableObjects/Narrative/Actors.meta
  UOP1_Project/Assets/ScriptableObjects/Narrative/Actors/BardHare.asset
  UOP1_Project/Assets/ScriptableObjects/Narrative/Actors/BardHare.asset.meta
  UOP1_Project/Assets/ScriptableObjects/Narrative/Actors/Hamlet.asset
  UOP1_Project/Assets/ScriptableObjects/Narrative/Actors/Hamlet.asset.meta
  UOP1_Project/Assets/ScriptableObjects/Narrative/Actors/Townsfolk.asset
  UOP1_Project/Assets/ScriptableObjects/Narrative/Actors/Townsfolk.asset.meta
  UOP1_Project/Assets/ScriptableObjects/Narrative/DialogueData.meta
  UOP1_Project/Assets/ScriptableObjects/Narrative/DialogueData/1.IntroToTown.meta
  UOP1_Project/Assets/ScriptableObjects/Narrative/DialogueData/1.IntroToTown/IntroDialogue.asset
  UOP1_Project/Assets/ScriptableObjects/Narrative/DialogueData/1.IntroToTown/IntroDialogue.asset.meta
  UOP1_Project/Assets/ScriptableObjects/Narrative/DialogueData/1.IntroToTown/Lines.meta
  UOP1_Project/Assets/ScriptableObjects/Narrative/DialogueData/1.IntroToTown/Lines/HeadToCentre.asset
  UOP1_Project/Assets/ScriptableObjects/Narrative/DialogueData/1.IntroToTown/Lines/HeadToCentre.asset.meta
  UOP1_Project/Assets/ScriptableObjects/Narrative/DialogueData/1.IntroToTown/Lines/Welcome.asset
  UOP1_Project/Assets/ScriptableObjects/Narrative/DialogueData/1.IntroToTown/Lines/Welcome.asset.meta
  UOP1_Project/Assets/ScriptableObjects/Narrative/DialogueData/GenericOink.asset
  UOP1_Project/Assets/ScriptableObjects/Narrative/DialogueData/GenericOink.asset.meta
  UOP1_Project/Assets/Scripts/CameraManager.cs
  UOP1_Project/Assets/Scripts/Cutscenes.meta
  UOP1_Project/Assets/Scripts/Cutscenes/CutsceneManager.cs
  UOP1_Project/Assets/Scripts/Cutscenes/CutsceneManager.cs.meta
  UOP1_Project/Assets/Scripts/Cutscenes/CutsceneTrigger.cs
  UOP1_Project/Assets/Scripts/Cutscenes/CutsceneTrigger.cs.meta
  UOP1_Project/Assets/Scripts/Cutscenes/DialogueControlTrack.meta
  UOP1_Project/Assets/Scripts/Cutscenes/DialogueControlTrack/DialogueBehaviour.cs
  UOP1_Project/Assets/Scripts/Cutscenes/DialogueControlTrack/DialogueBehaviour.cs.meta
  UOP1_Project/Assets/Scripts/Cutscenes/DialogueControlTrack/DialogueClip.cs
  UOP1_Project/Assets/Scripts/Cutscenes/DialogueControlTrack/DialogueClip.cs.meta
  UOP1_Project/Assets/Scripts/Cutscenes/DialogueControlTrack/DialogueMixerBehaviour.cs
  UOP1_Project/Assets/Scripts/Cutscenes/DialogueControlTrack/DialogueMixerBehaviour.cs.meta
  UOP1_Project/Assets/Scripts/Cutscenes/DialogueControlTrack/DialogueTrack.cs
  UOP1_Project/Assets/Scripts/Cutscenes/DialogueControlTrack/DialogueTrack.cs.meta
  UOP1_Project/Assets/Scripts/Dialogues.meta
  UOP1_Project/Assets/Scripts/Dialogues/ActorSO.cs
  UOP1_Project/Assets/Scripts/Dialogues/ActorSO.cs.meta
  UOP1_Project/Assets/Scripts/Dialogues/DialogueDataSO.cs
  UOP1_Project/Assets/Scripts/Dialogues/DialogueDataSO.cs.meta
  UOP1_Project/Assets/Scripts/Dialogues/DialogueLineSO.cs
  UOP1_Project/Assets/Scripts/Dialogues/DialogueLineSO.cs.meta
  UOP1_Project/Assets/Scripts/Dialogues/DialogueManager.cs
  UOP1_Project/Assets/Scripts/Dialogues/DialogueManager.cs.meta
  UOP1_Project/Assets/Scripts/Dialogues/Editor.meta
  UOP1_Project/Assets/Scripts/Dialogues/Editor/DialogueDataEditor.cs
  UOP1_Project/Assets/Scripts/Dialogues/Editor/DialogueDataEditor.cs.meta
  UOP1_Project/Assets/Scripts/Editor/ReorderableList.cs
  UOP1_Project/Assets/Scripts/Editor/ReorderableList.cs.meta
  UOP1_Project/Assets/Scripts/Input/GameInput.cs
  UOP1_Project/Assets/Scripts/Input/InputReader.cs
  UOP1_Project/Assets/Settings/Input/GameInput.inputactions
Labels: enhancement

#150 Toon Shader Wind effect addon
  UOP1_Project/Assets/Shaders/SubGraphs/ToonLightingModel.shadersubgraph
  UOP1_Project/Assets/Shaders/SubGraphs/ToonLightingModel.shadersubgraph.meta
  UOP1_Project/Assets/Shaders/SubGraphs/ToonShading.shadersubgraph
  UOP1_Project/Assets/Shaders/SubGraphs/ToonShading.shadersubgraph.meta
  UOP1_Project/Assets/Shaders/SubGraphs/ToonSpecular.shadersubgraph
  UOP1_Project/Assets/Shaders/SubGraphs/ToonSpecular.shadersubgraph.meta
  UOP1_Project/Assets/Shaders/SubGraphs/WindAddon.shadersubgraph
  UOP1_Project/Assets/Shaders/SubGraphs/WindAddon.shadersubgraph.meta
  UOP1_Project/Assets/Shaders/Toon.shadergraph
  UOP1_Project/Assets/Shaders/ToonPlusWind.shadergraph
  UOP1_Project/Assets/Shaders/ToonPlusWind.shadergraph.meta
Labels: art

#149 Fix Error when initializing StateMachine
  UOP1_Project/Assets/Scripts/StateMachine/Core/StateTransition.cs
  UOP1_Project/Assets/Scripts/StateMachine/ScriptableObjects/StateTransitionSO.cs
Labels: bug (important)

#114 Replaced StateTransitionSO with TransitionTableSO + Editor
  UOP1_Project/Assets/Prefabs/Pig.prefab
  UOP1_Project/Assets/ScriptableObjects/Protagonist/CharacterTransitionTable.asset
  UOP1_Project/Assets/ScriptableObjects/Protagonist/CharacterTransitionTable.asset.meta
  UOP1_Project/Assets/ScriptableObjects/Protagonist/Transitions.meta
  UOP1_Project/Assets/ScriptableObjects/Protagonist/Transitions/BeginJump.asset
  UOP1_Project/Assets/ScriptableObjects/Protagonist/Transitions/BeginJump.asset.meta
  UOP1_Project/Assets/ScriptableObjects/Protagonist/Transitions/BeginJumpDescent.asset
  UOP1_Project/Assets/ScriptableObjects/Protagonist/Transitions/HitHead.asset
  UOP1_Project/Assets/ScriptableObjects/Protagonist/Transitions/HitHead.asset.meta
  UOP1_Project/Assets/ScriptableObjects/Protagonist/Transitions/LandIdle.asset
  UOP1_Project/Assets/ScriptableObjects/Protagonist/Transitions/LandIdle.asset.meta
  UOP1_Project/Assets/ScriptableObjects/Protagonist/Transitions/LandWalking.asset
  UOP1_Project/Assets/ScriptableObjects/Protagonist/Transitions/LandWalking.asset.meta
  UOP1_Project/Assets/ScriptableObjects/Protagonist/Transitions/StartSliding.asset
  UOP1_Project/Assets/ScriptableObjects/Protagonist/Transitions/StartWalking.asset
  UOP1_Project/Assets/ScriptableObjects/Protagonist/Transitions/StartWalking.asset.meta
  UOP1_Project/Assets/ScriptableObjects/Protagonist/Transitions/StopSliding.asset
  UOP1_Project/Assets/ScriptableObjects/Protagonist/Transitions/StopSliding.asset.meta
  UOP1_Project/Assets/ScriptableObjects/Protagonist/Transitions/StopWalking.asset
  UOP1_Project/Assets/ScriptableObjects/Protagonist/Transitions/StopWalking.asset.meta
  UOP1_Project/Assets/Scripts/StateMachine/Core/StateMachine.cs
  UOP1_Project/Assets/Scripts/StateMachine/Editor.meta
  UOP1_Project/Assets/Scripts/StateMachine/Editor/AddTransitionHelper.cs
  UOP1_Project/Assets/Scripts/StateMachine/Editor/AddTransitionHelper.cs.meta
  UOP1_Project/Assets/Scripts/StateMachine/Editor/ContentStyle.cs
  UOP1_Project/Assets/Scripts/StateMachine/Editor/ContentStyle.cs.meta
  UOP1_Project/Assets/Scripts/StateMachine/Editor/SerializedTransition.cs
  UOP1_Project/Assets/Scripts/StateMachine/Editor/SerializedTransition.cs.meta
  UOP1_Project/Assets/Scripts/StateMachine/Editor/StateEditor.cs
  UOP1_Project/Assets/Scripts/StateMachine/Editor/StateEditor.cs.meta
  UOP1_Project/Assets/Scripts/StateMachine/Editor/TransitionDisplayHelper.cs
  UOP1_Project/Assets/Scripts/StateMachine/Editor/TransitionDisplayHelper.cs.meta
  UOP1_Project/Assets/Scripts/StateMachine/Editor/TransitionTableEditor.cs
  UOP1_Project/Assets/Scripts/StateMachine/Editor/TransitionTableEditor.cs.meta
  UOP1_Project/Assets/Scripts/StateMachine/ScriptableObjects/StateSO.cs
  UOP1_Project/Assets/Scripts/StateMachine/ScriptableObjects/TransitionTableSO.cs
  UOP1_Project/Assets/Scripts/StateMachine/ScriptableObjects/TransitionTableSO.cs.meta
Labels: enhancement

#131 Improved debugging for the state machine
  UOP1_Project/Assets/Prefabs/Pig.prefab
  UOP1_Project/Assets/Scripts/StateMachine/Core/State.cs
  UOP1_Project/Assets/Scripts/StateMachine/Core/StateAction.cs
  UOP1_Project/Assets/Scripts/StateMachine/Core/StateCondition.cs
  UOP1_Project/Assets/Scripts/StateMachine/Core/StateMachine.cs
  UOP1_Project/Assets/Scripts/StateMachine/Core/StateMachineDebugger.cs
  UOP1_Project/Assets/Scripts/StateMachine/Core/StateMachineDebugger.cs.meta
  UOP1_Project/Assets/Scripts/StateMachine/Core/StateTransition.cs
  UOP1_Project/Assets/Scripts/StateMachine/ScriptableObjects/StateActionSO.cs
  UOP1_Project/Assets/Scripts/StateMachine/ScriptableObjects/StateConditionSO.cs
  UOP1_Project/Assets/Scripts/StateMachine/ScriptableObjects/StateSO.cs
Labels: enhancement

#152 Repaint when selecting spawn location
  UOP1_Project/Assets/Scripts/ClickToPlaceHelper.cs
Labels: editor tool

#145 Beach whitebox
  UOP1_Project/Assets/Prefabs/PrototypingTree.prefab
  UOP1_Project/Assets/Prefabs/PrototypingTree.prefab.meta
  UOP1_Project/Assets/Prefabs/TreeRound.prefab
  UOP1_Project/Assets/Scenes/Whiteboxing/Beach.meta
  UOP1_Project/Assets/Scenes/Whiteboxing/Beach/Proposal_1.meta
  UOP1_Project/Assets/Scenes/Whiteboxing/Beach/Proposal_1/BardHare_Mat.mat
  UOP1_Project/Assets/Scenes/Whiteboxing/Beach/Proposal_1/BardHare_Mat.mat.meta
  UOP1_Project/Assets/Scenes/Whiteboxing/Beach/Proposal_1/BeachWhiteboxing_1_optimized.unity
  UOP1_Project/Assets/Scenes/Whiteboxing/Beach/Proposal_1/BeachWhiteboxing_1_optimized.unity.meta
  UOP1_Project/Assets/Scenes/Whiteboxing/Beach/Proposal_1/Tutorial_Mat.mat
  UOP1_Project/Assets/Scenes/Whiteboxing/Beach/Proposal_1/Tutorial_Mat.mat.meta
Labels: art

#155 Whiteboxing
  UOP1_Project/Assets/Smurjo whiteboxing.meta
  UOP1_Project/Assets/Smurjo whiteboxing/Town_Terrain_Material.mat
  UOP1_Project/Assets/Smurjo whiteboxing/Town_Terrain_Material.mat.meta
  UOP1_Project/Assets/Smurjo whiteboxing/Town_Terrain_Texture.JPG
  UOP1_Project/Assets/Smurjo whiteboxing/Town_Terrain_Texture.JPG.meta
  UOP1_Project/Assets/Smurjo whiteboxing/Truffleton_whiteboxing.unity
  UOP1_Project/Assets/Smurjo whiteboxing/Truffleton_whiteboxing.unity.meta
  UOP1_Project/Assets/Smurjo whiteboxing/oneStoreySmall.prefab
  UOP1_Project/Assets/Smurjo whiteboxing/oneStoreySmall.prefab.meta
  UOP1_Project/Assets/Smurjo whiteboxing/oneStoreyWide.prefab
  UOP1_Project/Assets/Smurjo whiteboxing/oneStoreyWide.prefab.meta
  UOP1_Project/Assets/Smurjo whiteboxing/town houses.prefab
  UOP1_Project/Assets/Smurjo whiteboxing/town houses.prefab.meta
  UOP1_Project/Assets/Smurjo whiteboxing/townTerrain.fbx
  UOP1_Project/Assets/Smurjo whiteboxing/townTerrain.fbx.meta
  UOP1_Project/Assets/Smurjo whiteboxing/twoStoreySmall.prefab
  UOP1_Project/Assets/Smurjo whiteboxing/twoStoreySmall.prefab.meta
  UOP1_Project/Assets/Smurjo whiteboxing/twoStoreyWide.prefab
  UOP1_Project/Assets/Smurjo whiteboxing/twoStoreyWide.prefab.meta
Labels: art

#173 OP Devlog #1: Toon shading
  UOP1_Project/Assets/Materials/Obstacles.mat
  UOP1_Project/Assets/Materials/White.mat
  UOP1_Project/Assets/Scenes/ToonShading.unity
  UOP1_Project/Assets/Scenes/ToonShadingSettings.lighting
  UOP1_Project/Assets/Scenes/ToonShadingSettings.lighting.meta
  UOP1_Project/Assets/Settings/Graphics/ToonRenderer.asset
  UOP1_Project/Assets/Shaders/CustomHLSL/CustomLighting.hlsl
  UOP1_Project/Assets/Shaders/CustomLighting.shadergraph
  UOP1_Project/Assets/Shaders/Shader Graphs_CustomLighting.mat
  UOP1_Project/Assets/Shaders/Shader Graphs_CustomLighting.mat.meta
  UOP1_Project/Packages/manifest.json
  UOP1_Project/Packages/packages-lock.json
  UOP1_Project/ProjectSettings/PackageManagerSettings.asset
  UOP1_Project/ProjectSettings/ProjectVersion.txt
  UOP1_Project/ProjectSettings/URPProjectSettings.asset
  UOP1_Project/ProjectSettings/VersionControlSettings.asset
  UOP1_Project/UserSettings/EditorUserSettings.asset
Labels: devlogs

#166 Delete unused metafile for Sound folder
  UOP1_Project/Assets/Scripts/Sound.meta
Labels: bug (minor)

#156 Added wind sensitiveness (green channel) on vertex color of nature FBX assets
  UOP1_Project/Assets/Art/TA/Nature/Bamboo/Bamboo.FBX
  UOP1_Project/Assets/Art/TA/Nature/Bamboo/BambooCane.mat
  UOP1_Project/Assets/Art/TA/Nature/Bush/Bush.FBX
  UOP1_Project/Assets/Art/TA/Nature/Bush/Bush.mat
  UOP1_Project/Assets/Art/TA/Nature/Fern/FernPlant.FBX
  UOP1_Project/Assets/Art/TA/Nature/Fern/FernPlant.mat
  UOP1_Project/Assets/Art/TA/Nature/Flower/Flower.FBX
  UOP1_Project/Assets/Art/TA/Nature/Flower/Flower.mat
  UOP1_Project/Assets/Art/TA/Nature/Grass/Grass.FBX
  UOP1_Project/Assets/Art/TA/Nature/Grass/Grass.mat
  UOP1_Project/Assets/Art/TA/Nature/Palm/Palm.FBX
  UOP1_Project/Assets/Art/TA/Nature/Palm/Palm.mat
  UOP1_Project/Assets/Art/TA/Nature/Tree/Tree.FBX
  UOP1_Project/Assets/Art/TA/Nature/Tree/Tree.mat
Labels: art

#174 Fix Water Shader: shallow water is now refrated
  UOP1_Project/Assets/Shaders/SubGraphs/DepthFade.shadersubgraph
  UOP1_Project/Assets/Shaders/Water.shadergraph
Labels: art

#172 Added fire shader and campfire
  UOP1_Project/Assets/Materials/Campfire.mat
  UOP1_Project/Assets/Materials/Campfire.mat.meta
  UOP1_Project/Assets/Materials/FireMask.png
  UOP1_Project/Assets/Materials/FireMask.png.meta
  UOP1_Project/Assets/Prefabs/Props/PotOverFire.prefab
  UOP1_Project/Assets/Shaders/Fire.shadergraph
  UOP1_Project/Assets/Shaders/Fire.shadergraph.meta
Labels: art

#177 Fix refraction for object above sea level
  UOP1_Project/Assets/Shaders/SubGraphs/DepthFade.shadersubgraph
  UOP1_Project/Assets/Shaders/Water.shadergraph
Labels: art

#162 Dialogue system event fix
  UOP1_Project/Assets/Scripts/Cutscenes/CutsceneManager.cs
  UOP1_Project/Assets/Scripts/Dialogues/DialogueManager.cs
  UOP1_Project/Assets/Scripts/Input/InputReader.cs
Labels: enhancement

#158 Added an Editor assembly for the FSM editor scripts
  UOP1_Project/Assets/Scripts/StateMachine/Editor/UOP1.StateMachine.Editor.asmdef
  UOP1_Project/Assets/Scripts/StateMachine/Editor/UOP1.StateMachine.Editor.asmdef.meta
Labels: enhancement

#164 Added cached conditions to the State Machine v2
  UOP1_Project/Assets/Prefabs/Pig.prefab
  UOP1_Project/Assets/ScriptableObjects/Protagonist/Conditions/HasHitHead.asset
  UOP1_Project/Assets/ScriptableObjects/Protagonist/Conditions/IsGrounded.asset
  UOP1_Project/Assets/ScriptableObjects/Protagonist/Conditions/IsHoldingJump.asset
  UOP1_Project/Assets/ScriptableObjects/Protagonist/Conditions/IsMoving.asset
  UOP1_Project/Assets/ScriptableObjects/Protagonist/Conditions/IsSliding.asset
  UOP1_Project/Assets/ScriptableObjects/Protagonist/Conditions/JumpHoldTimer.asset
  UOP1_Project/Assets/Scripts/Characters/StateMachine/Conditions/HasHitHeadConditionSO.cs
  UOP1_Project/Assets/Scripts/Characters/StateMachine/Conditions/IsCharacterControllerGroundedConditionSO.cs
  UOP1_Project/Assets/Scripts/Characters/StateMachine/Conditions/IsHoldingJumpConditionSO.cs
  UOP1_Project/Assets/Scripts/Characters/StateMachine/Conditions/IsMovingConditionSO.cs
  UOP1_Project/Assets/Scripts/Characters/StateMachine/Conditions/IsSlidingConditionSO.cs
  UOP1_Project/Assets/Scripts/Characters/StateMachine/Conditions/TimeElapsedConditionSO.cs
  UOP1_Project/Assets/Scripts/StateMachine/Core/State.cs
  UOP1_Project/Assets/Scripts/StateMachine/Core/StateAction.cs
  UOP1_Project/Assets/Scripts/StateMachine/Core/StateCondition.cs
  UOP1_Project/Assets/Scripts/StateMachine/Core/StateTransition.cs
  UOP1_Project/Assets/Scripts/StateMachine/ScriptableObjects/StateActionSO.cs
  UOP1_Project/Assets/Scripts/StateMachine/ScriptableObjects/StateConditionSO.cs
  UOP1_Project/Assets/Scripts/StateMachine/ScriptableObjects/StateSO.cs
  UOP1_Project/Assets/Scripts/StateMachine/ScriptableObjects/StateTransitionSO.cs
  UOP1_Project/Assets/Scripts/StateMachine/ScriptableObjects/StateTransitionSO.cs.meta
  UOP1_Project/Assets/Scripts/StateMachine/ScriptableObjects/TransitionTableSO.cs
Labels: enhancement

#169 fix: Project won't compile due to a reference to UnityEditor (#157)
  UOP1_Project/Assets/Scripts/ClickToPlaceHelper.cs
  UOP1_Project/Assets/Scripts/Editor/SpawnLocationEditor.cs
Labels: bug (critical)

#180 Fix/dialogue line not shown in custom timeline track
  UOP1_Project/Assets/Cutscenes/ExampleCutscene.playable
  UOP1_Project/Assets/Scenes/Examples.meta
  UOP1_Project/Assets/Scenes/Examples/Cutscenes.unity
  UOP1_Project/Assets/Scenes/Examples/Cutscenes.unity.meta
  UOP1_Project/Assets/Scripts/Cutscenes/DialogueControlTrack/DialogueBehaviour.cs
  UOP1_Project/Assets/Scripts/Cutscenes/DialogueControlTrack/DialogueMixerBehaviour.cs
  UOP1_Project/Assets/Scripts/Cutscenes/DialogueControlTrack/DialogueMixerBehaviour.cs.meta
Labels: bug (important)

#181 Remove unused ReorderableList implementation
  UOP1_Project/Assets/Scripts/Dialogues/Editor.meta
  UOP1_Project/Assets/Scripts/Dialogues/Editor/DialogueDataEditor.cs
  UOP1_Project/Assets/Scripts/Dialogues/Editor/DialogueDataEditor.cs.meta
  UOP1_Project/Assets/Scripts/Editor/ReorderableList.cs
  UOP1_Project/Assets/Scripts/Editor/ReorderableList.cs.meta
Labels: enhancement

#170 Earring for Townsfolk
  UOP1_Project/Assets/Art/TA/Accessories.meta
  UOP1_Project/Assets/Art/TA/Accessories/Earring.meta
  UOP1_Project/Assets/Art/TA/Accessories/Earring/Earring.fbx
  UOP1_Project/Assets/Art/TA/Accessories/Earring/Earring.fbx.meta
  UOP1_Project/Assets/Art/TA/Accessories/Earring/Earring.mat
  UOP1_Project/Assets/Art/TA/Accessories/Earring/Earring.mat.meta
  UOP1_Project/Assets/Art/TA/Accessories/Earring/Earring.prefab
  UOP1_Project/Assets/Art/TA/Accessories/Earring/Earring.prefab.meta
  UOP1_Project/Assets/Art/TA/Townsfolks Accessoires/Earring/Earring.obj
  UOP1_Project/Assets/Art/TA/Townsfolks Accessoires/Earring/Earring.prefab
  UOP1_Project/Assets/Scenes/ArtShowcase.unity
Labels: art

#168 Editor tool to replace GameObjects with Prefabs
  UOP1_Project/Assets/Scripts/Editor/ReplaceTool.cs
  UOP1_Project/Assets/Scripts/Editor/ReplaceTool.cs.meta
Labels: editor tool

#191 TransitionTableEditorWindow
  UOP1_Project/Assets/Scripts/StateMachine/Editor/AddTransitionHelper.cs
  UOP1_Project/Assets/Scripts/StateMachine/Editor/TransitionDisplayHelper.cs
  UOP1_Project/Assets/Scripts/StateMachine/Editor/TransitionTableEditor.cs
  UOP1_Project/Assets/Scripts/StateMachine/Editor/TransitionTableEditorWindow.cs
  UOP1_Project/Assets/Scripts/StateMachine/Editor/TransitionTableEditorWindow.cs.meta
  UOP1_Project/Assets/Scripts/StateMachine/Editor/TransitionTableEditorWindow.uss
  UOP1_Project/Assets/Scripts/StateMachine/Editor/TransitionTableEditorWindow.uss.meta
  UOP1_Project/Assets/Scripts/StateMachine/Editor/TransitionTableEditorWindow.uxml
  UOP1_Project/Assets/Scripts/StateMachine/Editor/TransitionTableEditorWindow.uxml.meta
Labels: enhancement

#159 Object pool simplifications
  UOP1_Project/Assets/Scripts/Factory/ComponentFactorySO.cs
  UOP1_Project/Assets/Scripts/Factory/ComponentFactorySO.cs.meta
  UOP1_Project/Assets/Scripts/Factory/FactorySO.cs
  UOP1_Project/Assets/Scripts/Pool/ComponentPoolSO.cs
  UOP1_Project/Assets/Scripts/Pool/Example/Assets/Example.unity
  UOP1_Project/Assets/Scripts/Pool/Example/Assets/Particles.prefab
  UOP1_Project/Assets/Scripts/Pool/Example/Assets/Particles.prefab.meta
  UOP1_Project/Assets/Scripts/Pool/Example/LocalPoolTester.cs
  UOP1_Project/Assets/Scripts/Pool/Example/ParticleFactorySO.cs
  UOP1_Project/Assets/Scripts/Pool/Example/ParticlePoolSO.cs
  UOP1_Project/Assets/Scripts/Pool/Example/PoolTester.cs
  UOP1_Project/Assets/Scripts/Pool/Example/PoolableParticle.cs
  UOP1_Project/Assets/Scripts/Pool/Example/PoolableParticle.cs.meta
  UOP1_Project/Assets/Scripts/Pool/IPoolable.cs
  UOP1_Project/Assets/Scripts/Pool/IPoolable.cs.meta
  UOP1_Project/Assets/Scripts/Pool/PoolSO.cs
Labels: enhancement

#192 Jumping, Landing and Walking Puff of Dust Particles
  UOP1_Project/Assets/ErizzoalbuquerqueStuff.meta
  UOP1_Project/Assets/ErizzoalbuquerqueStuff/JumpParticle.prefab
  UOP1_Project/Assets/ErizzoalbuquerqueStuff/JumpParticle.prefab.meta
  UOP1_Project/Assets/ErizzoalbuquerqueStuff/LandingParticle.prefab
  UOP1_Project/Assets/ErizzoalbuquerqueStuff/LandingParticle.prefab.meta
  UOP1_Project/Assets/ErizzoalbuquerqueStuff/PuffofDust.fbx
  UOP1_Project/Assets/ErizzoalbuquerqueStuff/PuffofDust.fbx.meta
  UOP1_Project/Assets/ErizzoalbuquerqueStuff/PuffofDustParticlesMaterial.mat
  UOP1_Project/Assets/ErizzoalbuquerqueStuff/PuffofDustParticlesMaterial.mat.meta
  UOP1_Project/Assets/ErizzoalbuquerqueStuff/TempPigParticlesController.cs
  UOP1_Project/Assets/ErizzoalbuquerqueStuff/TempPigParticlesController.cs.meta
  UOP1_Project/Assets/ErizzoalbuquerqueStuff/TestingParticlesScene.unity
  UOP1_Project/Assets/ErizzoalbuquerqueStuff/TestingParticlesScene.unity.meta
  UOP1_Project/Assets/ErizzoalbuquerqueStuff/WalkingParticle.prefab
  UOP1_Project/Assets/ErizzoalbuquerqueStuff/WalkingParticle.prefab.meta
  UOP1_Project/Assets/ErizzoalbuquerqueStuff/erizzoalbuquerque_PigChef.prefab
  UOP1_Project/Assets/ErizzoalbuquerqueStuff/erizzoalbuquerque_PigChef.prefab.meta
Labels: art

#202 Add Explicit Prewarm to Pool
  UOP1_Project/Assets/Scripts/Audio/AudioManager.cs
  UOP1_Project/Assets/Scripts/Audio/SoundEmitters/SoundEmitterPoolSO.cs
  UOP1_Project/Assets/Scripts/Pool/ComponentPoolSO.cs
  UOP1_Project/Assets/Scripts/Pool/Example/LocalPoolTester.cs
  UOP1_Project/Assets/Scripts/Pool/Example/ParticlePoolSO.cs
  UOP1_Project/Assets/Scripts/Pool/IPool.cs
  UOP1_Project/Assets/Scripts/Pool/PoolSO.cs
Labels: enhancement

#203 Editor window multiple event trigger fix
  UOP1_Project/Assets/Scripts/StateMachine/Editor/TransitionTableEditorWindow.cs
Labels: bug (minor)

#220 Create silhouette pass
  UOP1_Project/Assets/Materials/Character_Behind.mat
  UOP1_Project/Assets/Materials/Character_Behind.mat.meta
  UOP1_Project/Assets/Prefabs/Characters/BardHare.prefab
  UOP1_Project/Assets/Prefabs/Characters/PhoenixChick.prefab
  UOP1_Project/Assets/Prefabs/Characters/PigChef.prefab
  UOP1_Project/Assets/Prefabs/Characters/RockCritter.prefab
  UOP1_Project/Assets/Prefabs/Characters/Townsfolk_F.prefab
  UOP1_Project/Assets/Prefabs/Characters/Townsfolk_M.prefab
  UOP1_Project/Assets/Settings/Graphics/ToonRendererData.asset
  UOP1_Project/Assets/Shaders/Character_Behind.shadergraph
  UOP1_Project/Assets/Shaders/Character_Behind.shadergraph.meta
  UOP1_Project/ProjectSettings/TagManager.asset
Labels: enhancement

#210 Curls for female townsfolk and low quality sombrero
  UOP1_Project/Assets/Art/Accessories/Curls.meta
  UOP1_Project/Assets/Art/Accessories/Curls/curls.fbx
  UOP1_Project/Assets/Art/Accessories/Curls/curls.fbx.meta
  UOP1_Project/Assets/Art/Accessories/Curls/curls.prefab
  UOP1_Project/Assets/Art/Accessories/Curls/curls.prefab.meta
  UOP1_Project/Assets/Art/Accessories/Curls/red  curls.mat
  UOP1_Project/Assets/Art/Accessories/Curls/red  curls.mat.meta
  UOP1_Project/Assets/Art/Accessories/Curls/redHair_small.png
  UOP1_Project/Assets/Art/Accessories/Curls/redHair_small.png.meta
  UOP1_Project/Assets/Art/Accessories/EarCurls.meta
  UOP1_Project/Assets/Art/Accessories/EarCurls/earCurls.mat
  UOP1_Project/Assets/Art/Accessories/EarCurls/earCurls.mat.meta
  UOP1_Project/Assets/Art/Accessories/EarCurls/ear_curls Variant.prefab
  UOP1_Project/Assets/Art/Accessories/EarCurls/ear_curls Variant.prefab.meta
  UOP1_Project/Assets/Art/Accessories/EarCurls/ear_curls.fbx
  UOP1_Project/Assets/Art/Accessories/EarCurls/ear_curls.fbx.meta
  UOP1_Project/Assets/Art/Accessories/Sombrero.meta
  UOP1_Project/Assets/Art/Accessories/Sombrero/Sombrero.mat
  UOP1_Project/Assets/Art/Accessories/Sombrero/Sombrero.mat.meta
  UOP1_Project/Assets/Art/Accessories/Sombrero/Sombrero_texture.png
  UOP1_Project/Assets/Art/Accessories/Sombrero/Sombrero_texture.png.meta
  UOP1_Project/Assets/Art/Accessories/Sombrero/Sombrero_texture_narrow.png
  UOP1_Project/Assets/Art/Accessories/Sombrero/Sombrero_texture_narrow.png.meta
  UOP1_Project/Assets/Art/Accessories/Sombrero/low_quality_sombrero.fbx
  UOP1_Project/Assets/Art/Accessories/Sombrero/low_quality_sombrero.fbx.meta
  UOP1_Project/Assets/Art/Accessories/Sombrero/low_quality_sombrero.mat
  UOP1_Project/Assets/Art/Accessories/Sombrero/low_quality_sombrero.mat.meta
  UOP1_Project/Assets/Art/Accessories/Sombrero/low_quality_sombrero.prefab
  UOP1_Project/Assets/Art/Accessories/Sombrero/low_quality_sombrero.prefab.meta
  UOP1_Project/Assets/Art/Accessories/Sombrero/sombrero.fbx
  UOP1_Project/Assets/Art/Accessories/Sombrero/sombrero.fbx.meta
  UOP1_Project/Assets/Art/Accessories/Sombrero/sombrero.prefab
  UOP1_Project/Assets/Art/Accessories/Sombrero/sombrero.prefab.meta
  UOP1_Project/Assets/Scenes/townsfolk_wearing_Sombrero.unity
  UOP1_Project/Assets/Scenes/townsfolk_wearing_Sombrero.unity.meta
  UOP1_Project/Assets/Scenes/townsfolk_wearing_low_quality_Sombrero.unity
  UOP1_Project/Assets/Scenes/townsfolk_wearing_low_quality_Sombrero.unity.meta
Labels: art

#218 Created hammer model and texture
  UOP1_Project/Assets/Art/Accessories/HammerTool.meta
  UOP1_Project/Assets/Art/Accessories/HammerTool/Hammer.fbx
  UOP1_Project/Assets/Art/Accessories/HammerTool/Hammer.fbx.meta
  UOP1_Project/Assets/Art/Accessories/HammerTool/Hammer.mat
  UOP1_Project/Assets/Art/Accessories/HammerTool/Hammer.mat.meta
  UOP1_Project/Assets/Art/Accessories/HammerTool/HammerAlbedo.png
  UOP1_Project/Assets/Art/Accessories/HammerTool/HammerAlbedo.png.meta
  UOP1_Project/Assets/Prefabs/Accessories.meta
  UOP1_Project/Assets/Prefabs/Accessories/HammerTool.prefab
  UOP1_Project/Assets/Prefabs/Accessories/HammerTool.prefab.meta
Labels: art

#207 Created new Wildflowers
  UOP1_Project/Assets/Art/Nature/Flower/WildFlower.mat
  UOP1_Project/Assets/Art/Nature/Flower/WildFlower.mat.meta
  UOP1_Project/Assets/Art/Nature/Flower/WildFlower_Lamium.fbx
  UOP1_Project/Assets/Art/Nature/Flower/WildFlower_Lamium.fbx.meta
  UOP1_Project/Assets/Art/Nature/Flower/WildFlower_Leucanthemum.fbx
  UOP1_Project/Assets/Art/Nature/Flower/WildFlower_Leucanthemum.fbx.meta
  UOP1_Project/Assets/Art/Nature/Flower/WildFlower_Papaver.fbx
  UOP1_Project/Assets/Art/Nature/Flower/WildFlower_Papaver.fbx.meta
  UOP1_Project/Assets/Art/Nature/Flower/WildFlower_Purpurea.fbx
  UOP1_Project/Assets/Art/Nature/Flower/WildFlower_Purpurea.fbx.meta
  UOP1_Project/Assets/Art/Nature/Flower/WildFlower_UrticaUrens.fbx
  UOP1_Project/Assets/Art/Nature/Flower/WildFlower_UrticaUrens.fbx.meta
  UOP1_Project/Assets/Art/Nature/Flower/WildFlower_Valeriana.fbx
  UOP1_Project/Assets/Art/Nature/Flower/WildFlower_Valeriana.fbx.meta
  UOP1_Project/Assets/Art/Nature/Flower/WildFlowers_Albedo.tif
  UOP1_Project/Assets/Art/Nature/Flower/WildFlowers_Albedo.tif.meta
  UOP1_Project/Assets/Art/Nature/Flower/WildFlowers_MaskMap.tif
  UOP1_Project/Assets/Art/Nature/Flower/WildFlowers_MaskMap.tif.meta
  UOP1_Project/Assets/Art/Nature/Flower/Wildflower_Lapsana.fbx
  UOP1_Project/Assets/Art/Nature/Flower/Wildflower_Lapsana.fbx.meta
  UOP1_Project/Assets/Art/Nature/Flower/Wildflower_Myosotis.fbx
  UOP1_Project/Assets/Art/Nature/Flower/Wildflower_Myosotis.fbx.meta
  UOP1_Project/Assets/Art/Nature/Flower/Wildflower_Ranunculus.fbx
  UOP1_Project/Assets/Art/Nature/Flower/Wildflower_Ranunculus.fbx.meta
  UOP1_Project/Assets/Art/Nature/Flower/Wildflower_Urtica.fbx
  UOP1_Project/Assets/Art/Nature/Flower/Wildflower_Urtica.fbx.meta
  UOP1_Project/Assets/Prefabs/Nature/WildFlower_Lamium.prefab
  UOP1_Project/Assets/Prefabs/Nature/WildFlower_Lamium.prefab.meta
  UOP1_Project/Assets/Prefabs/Nature/WildFlower_Leucanthemum.prefab
  UOP1_Project/Assets/Prefabs/Nature/WildFlower_Leucanthemum.prefab.meta
  UOP1_Project/Assets/Prefabs/Nature/WildFlower_Papaver.prefab
  UOP1_Project/Assets/Prefabs/Nature/WildFlower_Papaver.prefab.meta
  UOP1_Project/Assets/Prefabs/Nature/WildFlower_Purpurea.prefab
  UOP1_Project/Assets/Prefabs/Nature/WildFlower_Purpurea.prefab.meta
  UOP1_Project/Assets/Prefabs/Nature/WildFlower_UrticaUrens.prefab
  UOP1_Project/Assets/Prefabs/Nature/WildFlower_UrticaUrens.prefab.meta
  UOP1_Project/Assets/Prefabs/Nature/WildFlower_Valeriana.prefab
  UOP1_Project/Assets/Prefabs/Nature/WildFlower_Valeriana.prefab.meta
  UOP1_Project/Assets/Prefabs/Nature/Wildflower_Lapsana.prefab
  UOP1_Project/Assets/Prefabs/Nature/Wildflower_Lapsana.prefab.meta
  UOP1_Project/Assets/Prefabs/Nature/Wildflower_Myosotis.prefab
  UOP1_Project/Assets/Prefabs/Nature/Wildflower_Myosotis.prefab.meta
  UOP1_Project/Assets/Prefabs/Nature/Wildflower_Ranunculus.prefab
  UOP1_Project/Assets/Prefabs/Nature/Wildflower_Ranunculus.prefab.meta
  UOP1_Project/Assets/Prefabs/Nature/Wildflower_Urtica.prefab
  UOP1_Project/Assets/Prefabs/Nature/Wildflower_Urtica.prefab.meta
Labels: art

#215 [Object Pool] Removed DontDestroyOnLoad & Add SetParent
  UOP1_Project/Assets/Scripts/Pool/ComponentPoolSO.cs
  UOP1_Project/Assets/Scripts/Pool/Example/LocalPoolTester.cs
  UOP1_Project/Assets/Scripts/Pool/PoolSO.cs
Labels: enhancement

#190 Plant Critter - Model, UV, Color, Rig and Animations
  UOP1_Project/Assets/Art/Characters/PlantCritter.meta
  UOP1_Project/Assets/Art/Characters/PlantCritter/Animation.meta
  UOP1_Project/Assets/Art/Characters/PlantCritter/Animation/PlantCritter.controller
  UOP1_Project/Assets/Art/Characters/PlantCritter/Animation/PlantCritter.controller.meta
  UOP1_Project/Assets/Art/Characters/PlantCritter/Animation/PlantCritter.fbx
  UOP1_Project/Assets/Art/Characters/PlantCritter/Animation/PlantCritter.fbx.meta
  UOP1_Project/Assets/Art/Characters/PlantCritter/PlantCritter.mat
  UOP1_Project/Assets/Art/Characters/PlantCritter/PlantCritter.mat.meta
  UOP1_Project/Assets/Art/Characters/PlantCritter/PlantCritter_Albedo.png
  UOP1_Project/Assets/Art/Characters/PlantCritter/PlantCritter_Albedo.png.meta
  UOP1_Project/Assets/Art/Characters/PlantCritter/PlantCritter_Specular.png
  UOP1_Project/Assets/Art/Characters/PlantCritter/PlantCritter_Specular.png.meta
  UOP1_Project/Assets/Prefabs/Characters/PlantCritter.prefab
  UOP1_Project/Assets/Prefabs/Characters/PlantCritter.prefab.meta
Labels: art

#200 Added SlimeCritter Model and new Toon variant for Slime Fresnel shinning
  UOP1_Project/Assets/Art/Characters/SlimeCritter.meta
  UOP1_Project/Assets/Art/Characters/SlimeCritter/Animation.meta
  UOP1_Project/Assets/Art/Characters/SlimeCritter/Animation/SlimeCritter.fbx
  UOP1_Project/Assets/Art/Characters/SlimeCritter/Animation/SlimeCritter.fbx.meta
  UOP1_Project/Assets/Art/Characters/SlimeCritter/SlimeCritterBody_Blue.mat
  UOP1_Project/Assets/Art/Characters/SlimeCritter/SlimeCritterBody_Blue.mat.meta
  UOP1_Project/Assets/Art/Characters/SlimeCritter/SlimeCritterBody_Brown.mat
  UOP1_Project/Assets/Art/Characters/SlimeCritter/SlimeCritterBody_Brown.mat.meta
  UOP1_Project/Assets/Art/Characters/SlimeCritter/SlimeCritterBody_Green.mat
  UOP1_Project/Assets/Art/Characters/SlimeCritter/SlimeCritterBody_Green.mat.meta
  UOP1_Project/Assets/Art/Characters/SlimeCritter/SlimeCritterBody_Orange.mat
  UOP1_Project/Assets/Art/Characters/SlimeCritter/SlimeCritterBody_Orange.mat.meta
  UOP1_Project/Assets/Art/Characters/SlimeCritter/SlimeCritterBody_Yellow.mat
  UOP1_Project/Assets/Art/Characters/SlimeCritter/SlimeCritterBody_Yellow.mat.meta
  UOP1_Project/Assets/Art/Characters/SlimeCritter/SlimeCritterEye.mat
  UOP1_Project/Assets/Art/Characters/SlimeCritter/SlimeCritterEye.mat.meta
  UOP1_Project/Assets/Art/Characters/SlimeCritter/SlimeCritter_Albedo.png
  UOP1_Project/Assets/Art/Characters/SlimeCritter/SlimeCritter_Albedo.png.meta
  UOP1_Project/Assets/Prefabs/Characters/SlimeCritterBlue.prefab
  UOP1_Project/Assets/Prefabs/Characters/SlimeCritterBlue.prefab.meta
  UOP1_Project/Assets/Prefabs/Characters/SlimeCritterBrown.prefab
  UOP1_Project/Assets/Prefabs/Characters/SlimeCritterBrown.prefab.meta
  UOP1_Project/Assets/Prefabs/Characters/SlimeCritterGreen.prefab
  UOP1_Project/Assets/Prefabs/Characters/SlimeCritterGreen.prefab.meta
  UOP1_Project/Assets/Prefabs/Characters/SlimeCritterOrange.prefab
  UOP1_Project/Assets/Prefabs/Characters/SlimeCritterOrange.prefab.meta
  UOP1_Project/Assets/Prefabs/Characters/SlimeCritterYellow.prefab
  UOP1_Project/Assets/Prefabs/Characters/SlimeCritterYellow.prefab.meta
  UOP1_Project/Assets/ProBuilder Data.meta
  UOP1_Project/Assets/Shaders/SubGraphs/MainLight.shadersubgraph
  UOP1_Project/Assets/Shaders/SubGraphs/ToonLightingModel.shadersubgraph
  UOP1_Project/Assets/Shaders/SubGraphs/ToonShading.shadersubgraph
  UOP1_Project/Assets/Shaders/Toon.shadergraph
  UOP1_Project/Assets/Shaders/Toon_Fresnel.shadergraph
  UOP1_Project/Assets/Shaders/Toon_Fresnel.shadergraph.meta
Labels: art

#224 State Machine QoL Improvements
  UOP1_Project/Assets/Scripts/StateMachine/Core/StateAction.cs
  UOP1_Project/Assets/Scripts/StateMachine/Core/StateCondition.cs
  UOP1_Project/Assets/Scripts/StateMachine/Core/StateMachine.cs
  UOP1_Project/Assets/Scripts/StateMachine/Debugging.meta
  UOP1_Project/Assets/Scripts/StateMachine/Debugging/StateMachineDebugger.cs
  UOP1_Project/Assets/Scripts/StateMachine/Debugging/StateMachineDebugger.cs.meta
  UOP1_Project/Assets/Scripts/StateMachine/Editor/Templates.meta
  UOP1_Project/Assets/Scripts/StateMachine/Editor/Templates/ScriptTemplates.cs
  UOP1_Project/Assets/Scripts/StateMachine/Editor/Templates/ScriptTemplates.cs.meta
  UOP1_Project/Assets/Scripts/StateMachine/Editor/Templates/StateAction.txt
  UOP1_Project/Assets/Scripts/StateMachine/Editor/Templates/StateAction.txt.meta
  UOP1_Project/Assets/Scripts/StateMachine/Editor/Templates/StateCondition.txt
  UOP1_Project/Assets/Scripts/StateMachine/Editor/Templates/StateCondition.txt.meta
  UOP1_Project/Assets/Scripts/StateMachine/Editor/Utilities.meta
  UOP1_Project/Assets/Scripts/StateMachine/Editor/Utilities/AddTransitionHelper.cs
  UOP1_Project/Assets/Scripts/StateMachine/Editor/Utilities/AddTransitionHelper.cs.meta
  UOP1_Project/Assets/Scripts/StateMachine/Editor/Utilities/ContentStyle.cs
  UOP1_Project/Assets/Scripts/StateMachine/Editor/Utilities/ContentStyle.cs.meta
  UOP1_Project/Assets/Scripts/StateMachine/Editor/Utilities/InitOnlyAttributeDrawer.cs
  UOP1_Project/Assets/Scripts/StateMachine/Editor/Utilities/InitOnlyAttributeDrawer.cs.meta
  UOP1_Project/Assets/Scripts/StateMachine/Editor/Utilities/SerializedTransition.cs
  UOP1_Project/Assets/Scripts/StateMachine/Editor/Utilities/SerializedTransition.cs.meta
  UOP1_Project/Assets/Scripts/StateMachine/Editor/Utilities/TransitionDisplayHelper.cs
  UOP1_Project/Assets/Scripts/StateMachine/Editor/Utilities/TransitionDisplayHelper.cs.meta
  UOP1_Project/Assets/Scripts/StateMachine/ScriptableObjects/StateConditionSO.cs
  UOP1_Project/Assets/Scripts/StateMachine/Utilities.meta
  UOP1_Project/Assets/Scripts/StateMachine/Utilities/InitOnlyAttribute.cs
  UOP1_Project/Assets/Scripts/StateMachine/Utilities/InitOnlyAttribute.cs.meta
Labels: enhancement

#239 Fix Plant Critter mesh scaling and name
  UOP1_Project/Assets/Art/Characters/PlantCritter/Animation/PlantCritter.fbx
  UOP1_Project/Assets/Prefabs/Characters/PlantCritter.prefab
Labels: art
