Repository UnityTechnologies/open-project-1, pull requests merged in 2020-10, with the labels that each got.

#17 Add Camera Sensitivity
  UOP1_Project/Assets/Scripts/CameraManager.cs
Labels: enhancement

#45 Fixed an issue regarding player jump not getting canceled in a few cases
  UOP1_Project/Assets/Scripts/Characters/Character.cs
Labels: bug (minor)

#31 Added custom inspector for GameScene ScriptableObjects
  UOP1_Project/Assets/Scripts/Editor.meta
  UOP1_Project/Assets/Scripts/Editor/GameSceneEditor.cs
  UOP1_Project/Assets/Scripts/Editor/GameSceneEditor.cs.meta
Labels: enhancement

#27 InputReader made into ScriptableObject asset
  UOP1_Project/Assets/Prefabs/Input Reader.asset
  UOP1_Project/Assets/Prefabs/Input Reader.asset.meta
  UOP1_Project/Assets/Prefabs/Pig.prefab
  UOP1_Project/Assets/Scenes/CharController.unity
  UOP1_Project/Assets/Scripts/InputReader.cs
Labels: !, enhancement

#26 Fixed steep surfaces bug and implemented sliding
  UOP1_Project/Assets/Scripts/Characters/Character.cs
Labels: bug (important)

#82 Added Discord Link
  README.md
Labels: enhancement

#109 Fixing events not being events
  UOP1_Project/Assets/Scripts/InputReader.cs
Labels: enhancement

#112 Fixed the StateTransitionSO error when grouping conditions
  UOP1_Project/Assets/Scripts/StateMachine/ScriptableObjects/StateTransitionSO.cs
Labels: bug (important)

#116 Fixed the character switching to JumpDescent state while walking
  UOP1_Project/Assets/ScriptableObjects/Protagonist/Transitions/BeginJumpDescent.asset
Labels: bug (important)

#113 Applied the tag EditorOnly to logical section GameObjects
  UOP1_Project/Assets/Scenes/CharController.unity
Labels: enhancement

#100 Inventory System Base (from official thread)
  UOP1_Project/Assets/Inventory.meta
  UOP1_Project/Assets/Inventory/ScriptableObjects.meta
  UOP1_Project/Assets/Inventory/ScriptableObjects/ItemTypes.meta
  UOP1_Project/Assets/Inventory/ScriptableObjects/ItemTypes/CharacterCustomization.asset
  UOP1_Project/Assets/Inventory/ScriptableObjects/ItemTypes/CharacterCustomization.asset.meta
  UOP1_Project/Assets/Inventory/ScriptableObjects/ItemTypes/Dish.asset
  UOP1_Project/Assets/Inventory/ScriptableObjects/ItemTypes/Dish.asset.meta
  UOP1_Project/Assets/Inventory/ScriptableObjects/ItemTypes/Ingredient.asset
  UOP1_Project/Assets/Inventory/ScriptableObjects/ItemTypes/Ingredient.asset.meta
  UOP1_Project/Assets/Inventory/ScriptableObjects/ItemTypes/Utensil.asset
  UOP1_Project/Assets/Inventory/ScriptableObjects/ItemTypes/Utensil.asset.meta
  UOP1_Project/Assets/Scripts/Inventory.meta
  UOP1_Project/Assets/Scripts/Inventory/InventoryController.cs
  UOP1_Project/Assets/Scripts/Inventory/InventoryController.cs.meta
  UOP1_Project/Assets/Scripts/Inventory/ItemInstance.cs
  UOP1_Project/Assets/Scripts/Inventory/ItemInstance.cs.meta
  UOP1_Project/Assets/Scripts/Inventory/ItemStack.cs
  UOP1_Project/Assets/Scripts/Inventory/ItemStack.cs.meta
  UOP1_Project/Assets/Scripts/Inventory/ScriptableObjects.meta
  UOP1_Project/Assets/Scripts/Inventory/ScriptableObjects/Inventory.cs
  UOP1_Project/Assets/Scripts/Inventory/ScriptableObjects/Inventory.cs.meta
  UOP1_Project/Assets/Scripts/Inventory/ScriptableObjects/Item.cs
  UOP1_Project/Assets/Scripts/Inventory/ScriptableObjects/Item.cs.meta
  UOP1_Project/Assets/Scripts/Inventory/ScriptableObjects/ItemType.cs
  UOP1_Project/Assets/Scripts/Inventory/ScriptableObjects/ItemType.cs.meta
Labels: enhancement

#129 Fix baked geometry becomes black when no dynamic geometry is on screen
  UOP1_Project/Assets/Shaders/CustomHLSL/CustomLighting.hlsl
Labels: bug (important)
