Repository UnityTechnologies/open-project-1, pull requests merged in 2021-06, with the labels that each got.

#444 Add multi_compile keywords to CustomLighting.hlsl, remove ShaderGraph keywords
  UOP1_Project/Assets/Shaders/Clouds.shadergraph
  UOP1_Project/Assets/Shaders/CustomHLSL/CustomLighting.hlsl
  UOP1_Project/Assets/Shaders/Toon.shadergraph
  UOP1_Project/Assets/Shaders/Toon_DetailMaskTint.shadergraph
  UOP1_Project/Assets/Shaders/Toon_Dissolve.shadergraph
  UOP1_Project/Assets/Shaders/Toon_DoubleSided.shadergraph
  UOP1_Project/Assets/Shaders/Toon_Ground_VertexColour.shadergraph
  UOP1_Project/Assets/Shaders/Toon_RandomPositionTint.shadergraph
  UOP1_Project/Assets/Shaders/Toon_Rocks.shadergraph
  UOP1_Project/Assets/Shaders/Toon_Slime.shadergraph
  UOP1_Project/Assets/Shaders/Toon_Wind.shadergraph
  UOP1_Project/Assets/Shaders/Unused/Toon_WithOutline.shadergraph
Labels: enhancement

#429 Added Railed Bridges and Earrings(Mesh, Material, and Prefabs)
  UOP1_Project/Assets/Art/Accessories/Earring_Pearl.meta
  UOP1_Project/Assets/Art/Accessories/Earring_Pearl/Earings_Pearl_Texture.png
  UOP1_Project/Assets/Art/Accessories/Earring_Pearl/Earings_Pearl_Texture.png.meta
  UOP1_Project/Assets/Art/Accessories/Earring_Pearl/Earring_Pearl.fbx
  UOP1_Project/Assets/Art/Accessories/Earring_Pearl/Earring_Pearl.fbx.meta
  UOP1_Project/Assets/Art/Accessories/Earring_Pearl/Earring_Pearl_Material.mat
  UOP1_Project/Assets/Art/Accessories/Earring_Pearl/Earring_Pearl_Material.mat.meta
  UOP1_Project/Assets/Art/Accessories/Earring_Stone.meta
  UOP1_Project/Assets/Art/Accessories/Earring_Stone/Earing_Stone_Metallic.png
  UOP1_Project/Assets/Art/Accessories/Earring_Stone/Earing_Stone_Metallic.png.meta
  UOP1_Project/Assets/Art/Accessories/Earring_Stone/Earings_Stone_Basemap.png
  UOP1_Project/Assets/Art/Accessories/Earring_Stone/Earings_Stone_Basemap.png.meta
  UOP1_Project/Assets/Art/Accessories/Earring_Stone/Earring_Stone.fbx
  UOP1_Project/Assets/Art/Accessories/Earring_Stone/Earring_Stone.fbx.meta
  UOP1_Project/Assets/Art/Accessories/Earring_Stone/Earring_Stone_Material.mat
  UOP1_Project/Assets/Art/Accessories/Earring_Stone/Earring_Stone_Material.mat.meta
  UOP1_Project/Assets/Art/Props/Railed_Bridges.meta
  UOP1_Project/Assets/Art/Props/Railed_Bridges/Railed_Long_Bridge.meta
  UOP1_Project/Assets/Art/Props/Railed_Bridges/Railed_Long_Bridge/Railed_Long_Bride_Texture.png
  UOP1_Project/Assets/Art/Props/Railed_Bridges/Railed_Long_Bridge/Railed_Long_Bride_Texture.png.meta
  UOP1_Project/Assets/Art/Props/Railed_Bridges/Railed_Long_Bridge/Railed_Long_Bridge_Collider.fbx
  UOP1_Project/Assets/Art/Props/Railed_Bridges/Railed_Long_Bridge/Railed_Long_Bridge_Collider.fbx.meta
  UOP1_Project/Assets/Art/Props/Railed_Bridges/Railed_Long_Bridge/Railed_Long_Bridge_Material.mat
  UOP1_Project/Assets/Art/Props/Railed_Bridges/Railed_Long_Bridge/Railed_Long_Bridge_Material.mat.meta
  UOP1_Project/Assets/Art/Props/Railed_Bridges/Railed_Long_Bridge/Railed_Long_Bridge_Mesh.fbx
  UOP1_Project/Assets/Art/Props/Railed_Bridges/Railed_Long_Bridge/Railed_Long_Bridge_Mesh.fbx.meta
  UOP1_Project/Assets/Art/Props/Railed_Bridges/Railed_Short_Bridge.meta
  UOP1_Project/Assets/Art/Props/Railed_Bridges/Railed_Short_Bridge/Railed_Short_Bridge_Collider.fbx
  UOP1_Project/Assets/Art/Props/Railed_Bridges/Railed_Short_Bridge/Railed_Short_Bridge_Collider.fbx.meta
  UOP1_Project/Assets/Art/Props/Railed_Bridges/Railed_Short_Bridge/Railed_Short_Bridge_Material.mat
  UOP1_Project/Assets/Art/Props/Railed_Bridges/Railed_Short_Bridge/Railed_Short_Bridge_Material.mat.meta
  UOP1_Project/Assets/Art/Props/Railed_Bridges/Railed_Short_Bridge/Railed_Short_Bridge_Mesh.fbx
  UOP1_Project/Assets/Art/Props/Railed_Bridges/Railed_Short_Bridge/Railed_Short_Bridge_Mesh.fbx.meta
  UOP1_Project/Assets/Art/Props/Railed_Bridges/Railed_Short_Bridge/Railed_Short_Bridge_Texture.png
  UOP1_Project/Assets/Art/Props/Railed_Bridges/Railed_Short_Bridge/Railed_Short_Bridge_Texture.png.meta
  UOP1_Project/Assets/Prefabs/Accessories/Earring_Pearl.prefab
  UOP1_Project/Assets/Prefabs/Accessories/Earring_Pearl.prefab.meta
  UOP1_Project/Assets/Prefabs/Accessories/Earring_Stone.prefab
  UOP1_Project/Assets/Prefabs/Accessories/Earring_Stone.prefab.meta
  UOP1_Project/Assets/Prefabs/Props/Railed_Bridge_Long.prefab
  UOP1_Project/Assets/Prefabs/Props/Railed_Bridge_Long.prefab.meta
  UOP1_Project/Assets/Prefabs/Props/Railed_Bridge_Short.prefab
  UOP1_Project/Assets/Prefabs/Props/Railed_Bridge_Short.prefab.meta
Labels: art

#441 Fixed Settings menu not properly populating
  UOP1_Project/Assets/Scripts/UI/Settings/UIPaginationFiller.cs
Labels: bug (important)

#425 Fix fade-in volume. When fade in, volume is restored to 1 not the vo…
  UOP1_Project/Assets/Scripts/Audio/SoundEmitters/SoundEmitter.cs
Labels: bug (important)

#451 Bugfix delete transition
  UOP1_Project/Assets/Scripts/StateMachine/Editor/TransitionTableEditor.cs
Labels: bug (important)

#454 Add camera shake on protagonist hit.
  UOP1_Project/Assets/Prefabs/Gameplay/CameraSystem.prefab
  UOP1_Project/Assets/ScriptableObjects/Events/Camera.meta
  UOP1_Project/Assets/ScriptableObjects/Events/Camera/CameraShakeEvent.asset
  UOP1_Project/Assets/ScriptableObjects/Events/Camera/CameraShakeEvent.asset.meta
  UOP1_Project/Assets/ScriptableObjects/StateMachine/Critters/PlantCritter/States/GettingHit.asset
  UOP1_Project/Assets/ScriptableObjects/StateMachine/Critters/SlimeRockCritter/States/GettingHit.asset
  UOP1_Project/Assets/ScriptableObjects/StateMachine/Protagonist/Actions/ShakeCamAction.asset
  UOP1_Project/Assets/ScriptableObjects/StateMachine/Protagonist/Actions/ShakeCamAction.asset.meta
  UOP1_Project/Assets/ScriptableObjects/StateMachine/Protagonist/States/GettingHit.asset
  UOP1_Project/Assets/Scripts/Camera/CameraManager.cs
  UOP1_Project/Assets/Scripts/Characters/StateMachine/Actions/ShakeCamActionSO.cs
  UOP1_Project/Assets/Scripts/Characters/StateMachine/Actions/ShakeCamActionSO.cs.meta
Labels: enhancement

#452 Add lightmap scale setter tool
  UOP1_Project/Assets/Scripts/EditorTools/LightmapScaleSetter.cs
  UOP1_Project/Assets/Scripts/EditorTools/LightmapScaleSetter.cs.meta
Labels: tool

#455 Stop audio cue when associated Component is destroyed
  UOP1_Project/Assets/Scripts/Audio/AudioCue.cs
Labels: bug (critical)

#458 Added Statue(Mesh, Material, and Prefabs)
  UOP1_Project/Assets/Art/Props/Statue.meta
  UOP1_Project/Assets/Art/Props/Statue/Statue_Material.mat
  UOP1_Project/Assets/Art/Props/Statue/Statue_Material.mat.meta
  UOP1_Project/Assets/Art/Props/Statue/Statue_Mesh.fbx
  UOP1_Project/Assets/Art/Props/Statue/Statue_Mesh.fbx.meta
  UOP1_Project/Assets/Art/Props/Statue/Statue_Texture.png
  UOP1_Project/Assets/Art/Props/Statue/Statue_Texture.png.meta
  UOP1_Project/Assets/Prefabs/TownStructures/Statue_Prefab.prefab
  UOP1_Project/Assets/Prefabs/TownStructures/Statue_Prefab.prefab.meta
Labels: art
