Repository UnityTechnologies/open-project-1, pull requests merged in 2021-04, with the labels that each got.

#390 Corrected Small Typo in Function Declaration
  UOP1_Project/Assets/Scripts/Inventory/ScriptableObjects/Inventory.cs
  UOP1_Project/Assets/Scripts/Inventory/UIInventoryManager.cs
Labels: bug (minor)

#392 Fixes #385 where no locale is selected in a build
  UOP1_Project/Assets/AddressableAssetsData/AssetGroups/Schemas/Localization-AssetTables_BundledAssetGroupSchema.asset
  UOP1_Project/Assets/AddressableAssetsData/AssetGroups/Schemas/Localization-Assets-Shared_BundledAssetGroupSchema.asset
  UOP1_Project/Assets/AddressableAssetsData/AssetGroups/Schemas/Localization-Assets-en_BundledAssetGroupSchema.asset
  UOP1_Project/Assets/AddressableAssetsData/AssetGroups/Schemas/Localization-Assets-fr_BundledAssetGroupSchema.asset
  UOP1_Project/Assets/AddressableAssetsData/AssetGroups/Schemas/Localization-Locales_BundledAssetGroupSchema.asset
  UOP1_Project/Assets/AddressableAssetsData/AssetGroups/Schemas/Localization-StringTables_BundledAssetGroupSchema.asset
Labels: bug (important)

#394 Added L0D Models for Townsfolk
  UOP1_Project/Assets/Art/Characters/Townsfolk_F/L0D/L0D.meta
  UOP1_Project/Assets/Art/Characters/Townsfolk_F/L0D/Townsfolk_F_L0D.fbx
  UOP1_Project/Assets/Art/Characters/Townsfolk_F/L0D/Townsfolk_F_L0D.fbx.meta
  UOP1_Project/Assets/Art/Characters/Townsfolk_F/L0D/Townsfolk_F_L0D_Prefab.prefab
  UOP1_Project/Assets/Art/Characters/Townsfolk_F/L0D/Townsfolk_F_L0D_Prefab.prefab.meta
  UOP1_Project/Assets/Art/Characters/Townsfolk_M/L0D/L0D.meta
  UOP1_Project/Assets/Art/Characters/Townsfolk_M/L0D/Townsfolk_M_L0D.fbx
  UOP1_Project/Assets/Art/Characters/Townsfolk_M/L0D/Townsfolk_M_L0D.fbx.meta
  UOP1_Project/Assets/Art/Characters/Townsfolk_M/L0D/Townsfolk_M_L0D_Prefab.prefab
  UOP1_Project/Assets/Art/Characters/Townsfolk_M/L0D/Townsfolk_M_L0D_Prefab.prefab.meta
Labels: art
