Repository UnityTechnologies/open-project-1, pull requests merged in 2021-02, with the labels that each got.

#339 Fix input caching
  UOP1_Project/Assets/ScriptableObjects/StateMachine/Protagonist/Actions/ClearInputCache_OnEnter.asset
  UOP1_Project/Assets/ScriptableObjects/StateMachine/Protagonist/Actions/ClearInputCache_OnEnter.asset.meta
  UOP1_Project/Assets/ScriptableObjects/StateMachine/Protagonist/States/Idle.asset
  UOP1_Project/Assets/ScriptableObjects/StateMachine/Protagonist/States/Walking.asset
  UOP1_Project/Assets/Scripts/Characters/StateMachine/Actions/ClearInputCache_OnEnterSO.cs
  UOP1_Project/Assets/Scripts/Characters/StateMachine/Actions/ClearInputCache_OnEnterSO.cs.meta
  UOP1_Project/Assets/Scripts/Interaction/InteractionManager.cs
Labels: bug (important)

#347 Fixed white crispy outline in Play mode around object over water
  UOP1_Project/Assets/Shaders/Water.shadergraph
Labels: bug (important)

#354 fix for camera Lerps into place
  UOP1_Project/Assets/Scripts/CameraManager.cs
Labels: bug (important)

#311 UI Fade in and out code and implementation
  UOP1_Project/Assets/Scenes/PersistentManagers.unity
  UOP1_Project/Assets/ScriptableObjects/Events/UI/FadeChannelSO.asset
  UOP1_Project/Assets/ScriptableObjects/Events/UI/FadeChannelSO.asset.meta
  UOP1_Project/Assets/Scripts/Events/ScriptableObjects/UI/FadeChannelSO.cs
  UOP1_Project/Assets/Scripts/Events/ScriptableObjects/UI/FadeChannelSO.cs.meta
  UOP1_Project/Assets/Scripts/UI/FadeManager.cs
  UOP1_Project/Assets/Scripts/UI/FadeManager.cs.meta
Labels: enhancement

#345 Added Slime Critter droplets when moving
  UOP1_Project/Assets/Art/Characters/SlimeCritter/SlimeCritterDroplet.fbx
  UOP1_Project/Assets/Art/Characters/SlimeCritter/SlimeCritterDroplet.fbx.meta
  UOP1_Project/Assets/Prefabs/Characters/Critter/TrailingDoplets.prefab
  UOP1_Project/Assets/Prefabs/Characters/Critter/TrailingDoplets.prefab.meta
  UOP1_Project/Assets/Prefabs/Characters/SlimeCritter_Base.prefab
Labels: art

#367 AudioManager UnregisterChannel fix
  UOP1_Project/Assets/Scripts/Audio/AudioManager.cs
Labels: bug (important)

#362 Shading Model - Emission Support
  UOP1_Project/Assets/Shaders/SubGraphs/Emission.shadersubgraph
  UOP1_Project/Assets/Shaders/SubGraphs/Emission.shadersubgraph.meta
  UOP1_Project/Assets/Shaders/Toon.shadergraph
Labels: art

#286 Added Modular Save System functionality
  UOP1_Project/Assets/Scripts/SaveSystem.meta
  UOP1_Project/Assets/Scripts/SaveSystem/Save.cs
  UOP1_Project/Assets/Scripts/SaveSystem/Save.cs.meta
  UOP1_Project/Assets/Scripts/SaveSystem/SaveSystem.cs
  UOP1_Project/Assets/Scripts/SaveSystem/SaveSystem.cs.meta
  UOP1_Project/Assets/Scripts/SaveSystem/TestScript.meta
  UOP1_Project/Assets/Scripts/SaveSystem/TestScript/TestScript.cs
  UOP1_Project/Assets/Scripts/SaveSystem/TestScript/TestScript.cs.meta
Labels: enhancement

#356 Added slash effect when player is triggering an attack
  UOP1_Project/Assets/Art/Characters/PigChef/Animation/CaneHit.anim
  UOP1_Project/Assets/Art/Characters/PigChef/Animation/CaneHit2.anim
  UOP1_Project/Assets/Art/Characters/PigChef/Animation/PigChef.controller
  UOP1_Project/Assets/Art/Characters/PigChef/Effect.meta
  UOP1_Project/Assets/Art/Characters/PigChef/Effect/Slash.fbx
  UOP1_Project/Assets/Art/Characters/PigChef/Effect/Slash.fbx.meta
  UOP1_Project/Assets/Art/Characters/PigChef/Effect/Slash.png
  UOP1_Project/Assets/Art/Characters/PigChef/Effect/Slash.png.meta
  UOP1_Project/Assets/Art/Characters/PigChef/Effect/SlashEffect.prefab
  UOP1_Project/Assets/Art/Characters/PigChef/Effect/SlashEffect.prefab.meta
  UOP1_Project/Assets/Art/Characters/PigChef/Effect/SlashMaterial.mat
  UOP1_Project/Assets/Art/Characters/PigChef/Effect/SlashMaterial.mat.meta
  UOP1_Project/Assets/Prefabs/Characters/PigChef.prefab
  UOP1_Project/Assets/Scripts/Characters/StateMachine/Actions/ControlWalkingParticlesActionSO.cs
  UOP1_Project/Assets/Scripts/Characters/StateMachine/Actions/DestroyEntitySO.cs
  UOP1_Project/Assets/Scripts/Characters/StateMachine/Actions/PlayJumpParticlesActionSO.cs
  UOP1_Project/Assets/Scripts/Characters/StateMachine/Actions/PlayLandParticlesActionSO.cs
  UOP1_Project/Assets/Scripts/Characters/StateMachine/Actions/PlayLiftoffJumpParticlesActionSO.cs
  UOP1_Project/Assets/Scripts/Effects/PlayerEffectController.cs
  UOP1_Project/Assets/Scripts/Effects/PlayerEffectController.cs.meta
  UOP1_Project/Assets/Shaders/Slash.shadergraph
  UOP1_Project/Assets/Shaders/Slash.shadergraph.meta
Labels: art
