Repository UnityTechnologies/open-project-1, pull requests merged in 2021-01, with the labels that each got.

#265 Making GameSceneSO more reliable
  UOP1_Project/Assets/ScriptableObjects/SceneData/Initialization.asset
  UOP1_Project/Assets/ScriptableObjects/SceneData/Locations/Beach.asset
  UOP1_Project/Assets/ScriptableObjects/SceneData/Locations/Forest.asset
  UOP1_Project/Assets/ScriptableObjects/SceneData/Locations/TestingGround.asset
  UOP1_Project/Assets/ScriptableObjects/SceneData/Menus/MainMenu.asset
  UOP1_Project/Assets/Scripts/Editor/GameSceneSOEditor.cs
  UOP1_Project/Assets/Scripts/SceneManagement/EditorInitialisationLoader.cs
  UOP1_Project/Assets/Scripts/SceneManagement/LocationLoader.cs
  UOP1_Project/Assets/Scripts/SceneManagement/ScriptableObjects/GameSceneSO.cs
  UOP1_Project/Assets/Scripts/SceneManagement/ScriptableObjects/GameSceneSOEditor.cs
  UOP1_Project/Assets/Scripts/SceneManagement/ScriptableObjects/GameSceneSOEditor.cs.meta
Labels: editor tool

#277 ReplaceTool selection and sibling index fix
  UOP1_Project/Assets/Scripts/Editor/ReplaceTool.cs
Labels: enhancement

#274 Fix SceneAccessTool build fail issue
  UOP1_Project/Assets/Scripts/Attributes.meta
  UOP1_Project/Assets/Scripts/Attributes/Editor.meta
  UOP1_Project/Assets/Scripts/Attributes/Editor/ReadOnlyDrawer.cs
  UOP1_Project/Assets/Scripts/Attributes/Editor/ReadOnlyDrawer.cs.meta
  UOP1_Project/Assets/Scripts/Attributes/ReadOnlyAttribute.cs
  UOP1_Project/Assets/Scripts/Attributes/ReadOnlyAttribute.cs.meta
  UOP1_Project/Assets/Scripts/Editor/SceneAccessTool.cs
  UOP1_Project/Assets/Scripts/Editor/SceneAccessTool.cs.meta
  UOP1_Project/Assets/Scripts/SceneManagement/ScriptableObjects/SceneAccessHolderSO.cs
Labels: bug (important)

#294 General Map Whiteboxing_1
  UOP1_Project/Assets/Art/Accessories/EarCurls/earCurls.mat
  UOP1_Project/Assets/Art/Accessories/Moustache/moustache.mat
  UOP1_Project/Assets/Scenes/Skybox/ClearSky.meta
  UOP1_Project/Assets/Scenes/Whiteboxing/2. Glade - Forest 1.meta
  UOP1_Project/Assets/Scenes/Whiteboxing/4. Forest Maze.meta
  UOP1_Project/Assets/Scenes/Whiteboxing/5. Rocky Path.meta
  UOP1_Project/Assets/Scenes/Whiteboxing/GeneralMap.meta
  UOP1_Project/Assets/Scenes/Whiteboxing/GeneralMap/Proposal 1.meta
  UOP1_Project/Assets/Scenes/Whiteboxing/GeneralMap/Proposal 1/CloudRotation.cs
  UOP1_Project/Assets/Scenes/Whiteboxing/GeneralMap/Proposal 1/CloudRotation.cs.meta
  UOP1_Project/Assets/Scenes/Whiteboxing/GeneralMap/Proposal 1/GeneralMap_Materials.meta
  UOP1_Project/Assets/Scenes/Whiteboxing/GeneralMap/Proposal 1/GeneralMap_Materials/Mtl_Cloud.mat
  UOP1_Project/Assets/Scenes/Whiteboxing/GeneralMap/Proposal 1/GeneralMap_Materials/Mtl_Cloud.mat.meta
  UOP1_Project/Assets/Scenes/Whiteboxing/GeneralMap/Proposal 1/GeneralMap_Materials/Mtl_Descriptions.mat
  UOP1_Project/Assets/Scenes/Whiteboxing/GeneralMap/Proposal 1/GeneralMap_Materials/Mtl_Descriptions.mat.meta
  UOP1_Project/Assets/Scenes/Whiteboxing/GeneralMap/Proposal 1/GeneralMap_Materials/Mtl_Forest.mat
  UOP1_Project/Assets/Scenes/Whiteboxing/GeneralMap/Proposal 1/GeneralMap_Materials/Mtl_Forest.mat.meta
  UOP1_Project/Assets/Scenes/Whiteboxing/GeneralMap/Proposal 1/GeneralMap_Materials/Mtl_Glade.mat
  UOP1_Project/Assets/Scenes/Whiteboxing/GeneralMap/Proposal 1/GeneralMap_Materials/Mtl_Glade.mat.meta
  UOP1_Project/Assets/Scenes/Whiteboxing/GeneralMap/Proposal 1/GeneralMap_Materials/Mtl_Mountain.mat
  UOP1_Project/Assets/Scenes/Whiteboxing/GeneralMap/Proposal 1/GeneralMap_Materials/Mtl_Mountain.mat.meta
  UOP1_Project/Assets/Scenes/Whiteboxing/GeneralMap/Proposal 1/GeneralMap_Materials/Mtl_Placeholders.mat
  UOP1_Project/Assets/Scenes/Whiteboxing/GeneralMap/Proposal 1/GeneralMap_Materials/Mtl_Placeholders.mat.meta
  UOP1_Project/Assets/Scenes/Whiteboxing/GeneralMap/Proposal 1/GeneralMap_Materials/Mtl_RockPath_Down.mat
  UOP1_Project/Assets/Scenes/Whiteboxing/GeneralMap/Proposal 1/GeneralMap_Materials/Mtl_RockPath_Down.mat.meta
  UOP1_Project/Assets/Scenes/Whiteboxing/GeneralMap/Proposal 1/GeneralMap_Materials/Mtl_RockPath_Up.mat
  UOP1_Project/Assets/Scenes/Whiteboxing/GeneralMap/Proposal 1/GeneralMap_Materials/Mtl_RockPath_Up.mat.meta
  UOP1_Project/Assets/Scenes/Whiteboxing/GeneralMap/Proposal 1/GeneralMap_Materials/Mtl_Water.mat
  UOP1_Project/Assets/Scenes/Whiteboxing/GeneralMap/Proposal 1/GeneralMap_Materials/Mtl_Water.mat.meta
  UOP1_Project/Assets/Scenes/Whiteboxing/GeneralMap/Proposal 1/GeneralMap_Proposal 1.unity.meta
Labels: art

#283 Fixed colliders on the trees
  UOP1_Project/Assets/Prefabs/GameplayEssentials/CameraSystem.prefab
  UOP1_Project/Assets/Prefabs/Nature/Trees/Tree.prefab
  UOP1_Project/Assets/Prefabs/Nature/Trees/Tree2.prefab
  UOP1_Project/Assets/Prefabs/Nature/Trees/TreeBig.prefab
  UOP1_Project/Assets/Prefabs/Nature/Trees/Tree_Flat.prefab
  UOP1_Project/Assets/Prefabs/Nature/Trees/Tree_Mushroom.prefab
  UOP1_Project/Assets/Prefabs/Nature/Trees/Tree_Swirl.prefab
  UOP1_Project/ProjectSettings/DynamicsManager.asset
  UOP1_Project/ProjectSettings/TagManager.asset
Labels: bug (important), enhancement

#291 A Wooden Bench for sitting and eating.
  UOP1_Project/Assets/Art/Props/WoodenBench.meta
  UOP1_Project/Assets/Art/Props/WoodenBench/BenchTextureCombined2.png
  UOP1_Project/Assets/Art/Props/WoodenBench/BenchTextureCombined2.png.meta
  UOP1_Project/Assets/Art/Props/WoodenBench/WoodenBench.fbx
  UOP1_Project/Assets/Art/Props/WoodenBench/WoodenBench.fbx.meta
  UOP1_Project/Assets/Art/Props/WoodenBench/WoodenBench.mat
  UOP1_Project/Assets/Art/Props/WoodenBench/WoodenBench.mat.meta
  UOP1_Project/Assets/Prefabs/Furniture/WoodenBench.prefab
  UOP1_Project/Assets/Prefabs/Furniture/WoodenBench.prefab.meta
Labels: art

#241 Added initial plant critter behavior
  UOP1_Project/Assets/Prefabs/Characters/PlantCritter.prefab
  UOP1_Project/Assets/ScriptableObjects/StateMachine/Enemies.meta
  UOP1_Project/Assets/ScriptableObjects/StateMachine/Enemies/PlantCritter.meta
  UOP1_Project/Assets/ScriptableObjects/StateMachine/Enemies/PlantCritter/Actions.meta
  UOP1_Project/Assets/ScriptableObjects/StateMachine/Enemies/PlantCritter/Actions/FaceProtagonist.asset
  UOP1_Project/Assets/ScriptableObjects/StateMachine/Enemies/PlantCritter/Actions/FaceProtagonist.asset.meta
  UOP1_Project/Assets/ScriptableObjects/StateMachine/Enemies/PlantCritter/Actions/SetFalseAnimatorUnderAlert.asset
  UOP1_Project/Assets/ScriptableObjects/StateMachine/Enemies/PlantCritter/Actions/SetFalseAnimatorUnderAlert.asset.meta
  UOP1_Project/Assets/ScriptableObjects/StateMachine/Enemies/PlantCritter/Actions/SetTrueAnimatorUnderAlert.asset
  UOP1_Project/Assets/ScriptableObjects/StateMachine/Enemies/PlantCritter/Actions/SetTrueAnimatorUnderAlert.asset.meta
  UOP1_Project/Assets/ScriptableObjects/StateMachine/Enemies/PlantCritter/Actions/TriggerAnimatorAttack.asset
  UOP1_Project/Assets/ScriptableObjects/StateMachine/Enemies/PlantCritter/Actions/TriggerAnimatorAttack.asset.meta
  UOP1_Project/Assets/ScriptableObjects/StateMachine/Enemies/PlantCritter/Conditions.meta
  UOP1_Project/Assets/ScriptableObjects/StateMachine/Enemies/PlantCritter/Conditions/ProtagonistInAlertZone.asset
  UOP1_Project/Assets/ScriptableObjects/StateMachine/Enemies/PlantCritter/Conditions/ProtagonistInAlertZone.asset.meta
  UOP1_Project/Assets/ScriptableObjects/StateMachine/Enemies/PlantCritter/Conditions/ProtagonistInAttackZone.asset
  UOP1_Project/Assets/ScriptableObjects/StateMachine/Enemies/PlantCritter/Conditions/ProtagonistInAttackZone.asset.meta
  UOP1_Project/Assets/ScriptableObjects/StateMachine/Enemies/PlantCritter/Conditions/Time_AttackDuration.asset
  UOP1_Project/Assets/ScriptableObjects/StateMachine/Enemies/PlantCritter/Conditions/Time_AttackDuration.asset.meta
  UOP1_Project/Assets/ScriptableObjects/StateMachine/Enemies/PlantCritter/Conditions/Time_PlantAttackReload.asset
  UOP1_Project/Assets/ScriptableObjects/StateMachine/Enemies/PlantCritter/Conditions/Time_PlantAttackReload.asset.meta
  UOP1_Project/Assets/ScriptableObjects/StateMachine/Enemies/PlantCritter/Conditions/Time_PlantSpawning.asset
  UOP1_Project/Assets/ScriptableObjects/StateMachine/Enemies/PlantCritter/Conditions/Time_PlantSpawning.asset.meta
  UOP1_Project/Assets/ScriptableObjects/StateMachine/Enemies/PlantCritter/PlantCritter_TransitionTable.asset
  UOP1_Project/Assets/ScriptableObjects/StateMachine/Enemies/PlantCritter/PlantCritter_TransitionTable.asset.meta
  UOP1_Project/Assets/ScriptableObjects/StateMachine/Enemies/PlantCritter/States.meta
  UOP1_Project/Assets/ScriptableObjects/StateMachine/Enemies/PlantCritter/States/Alert.asset
  UOP1_Project/Assets/ScriptableObjects/StateMachine/Enemies/PlantCritter/States/Alert.asset.meta
  UOP1_Project/Assets/ScriptableObjects/StateMachine/Enemies/PlantCritter/States/Attack.asset
  UOP1_Project/Assets/ScriptableObjects/StateMachine/Enemies/PlantCritter/States/Attack.asset.meta
  UOP1_Project/Assets/ScriptableObjects/StateMachine/Enemies/PlantCritter/States/Dying.asset
  UOP1_Project/Assets/ScriptableObjects/StateMachine/Enemies/PlantCritter/States/Dying.asset.meta
  UOP1_Project/Assets/ScriptableObjects/StateMachine/Enemies/PlantCritter/States/Fighting.asset
  UOP1_Project/Assets/ScriptableObjects/StateMachine/Enemies/PlantCritter/States/Fighting.asset.meta
  UOP1_Project/Assets/ScriptableObjects/StateMachine/Enemies/PlantCritter/States/GettingHit.asset
  UOP1_Project/Assets/ScriptableObjects/StateMachine/Enemies/PlantCritter/States/GettingHit.asset.meta
  UOP1_Project/Assets/ScriptableObjects/StateMachine/Enemies/PlantCritter/States/Idle.asset
  UOP1_Project/Assets/ScriptableObjects/StateMachine/Enemies/PlantCritter/States/Idle.asset.meta
  UOP1_Project/Assets/ScriptableObjects/StateMachine/Enemies/PlantCritter/States/Spawning.asset
  UOP1_Project/Assets/ScriptableObjects/StateMachine/Enemies/PlantCritter/States/Spawning.asset.meta
  UOP1_Project/Assets/Scripts/Characters/Critter.cs
  UOP1_Project/Assets/Scripts/Characters/Critter.cs.meta
  UOP1_Project/Assets/Scripts/Characters/StateMachine/Actions/FaceProtagonistSO.cs
  UOP1_Project/Assets/Scripts/Characters/StateMachine/Actions/FaceProtagonistSO.cs.meta
  UOP1_Project/Assets/Scripts/Characters/StateMachine/Conditions/HasReceivedEventSO.cs
  UOP1_Project/Assets/Scripts/Characters/StateMachine/Conditions/HasReceivedEventSO.cs.meta
  UOP1_Project/Assets/Scripts/Characters/StateMachine/Conditions/PlayerIsInZoneSO.cs
  UOP1_Project/Assets/Scripts/Characters/StateMachine/Conditions/PlayerIsInZoneSO.cs.meta
  UOP1_Project/Assets/Scripts/Characters/ZoneTriggerController.cs
  UOP1_Project/Assets/Scripts/Characters/ZoneTriggerController.cs.meta
  UOP1_Project/Assets/Scripts/SpawnSystem.cs
Labels: enhancement

#284 Allow multiple entry/exit points in Locations
  UOP1_Project/Assets/Prefabs/GameplayEssentials/Entrance.prefab
  UOP1_Project/Assets/Prefabs/GameplayEssentials/Entrance.prefab.meta
  UOP1_Project/Assets/Prefabs/GameplayEssentials/SpawnSystem.prefab
  UOP1_Project/Assets/Scenes/Locations/Beach.unity
  UOP1_Project/Assets/Scenes/Locations/Forest.unity
  UOP1_Project/Assets/Scenes/TestingGround.unity
  UOP1_Project/Assets/ScriptableObjects/RuntimeAnchors/PathTaken.asset
  UOP1_Project/Assets/ScriptableObjects/RuntimeAnchors/PathTaken.asset.meta
  UOP1_Project/Assets/ScriptableObjects/SceneData/Paths.meta
  UOP1_Project/Assets/ScriptableObjects/SceneData/Paths/BetweenBeachAndForest.asset
  UOP1_Project/Assets/ScriptableObjects/SceneData/Paths/BetweenBeachAndForest.asset.meta
  UOP1_Project/Assets/ScriptableObjects/SceneData/Paths/BetweenBeachAndTestingGround.asset
  UOP1_Project/Assets/ScriptableObjects/SceneData/Paths/BetweenBeachAndTestingGround.asset.meta
  UOP1_Project/Assets/Scripts/RuntimeAnchors/PathAnchor.cs
  UOP1_Project/Assets/Scripts/RuntimeAnchors/PathAnchor.cs.meta
  UOP1_Project/Assets/Scripts/SceneManagement/LocationEntrance.cs
  UOP1_Project/Assets/Scripts/SceneManagement/LocationEntrance.cs.meta
  UOP1_Project/Assets/Scripts/SceneManagement/LocationExit.cs
  UOP1_Project/Assets/Scripts/SceneManagement/ScriptableObjects/PathSO.cs
  UOP1_Project/Assets/Scripts/SceneManagement/ScriptableObjects/PathSO.cs.meta
  UOP1_Project/Assets/Scripts/SpawnSystem.cs
  UOP1_Project/ProjectSettings/TagManager.asset
Labels: enhancement

#298 Corrected plant critter state machine to be aligned with animator
  UOP1_Project/Assets/ScriptableObjects/StateMachine/Enemies/PlantCritter/Conditions/Timer_PlantFainting.asset
  UOP1_Project/Assets/ScriptableObjects/StateMachine/Enemies/PlantCritter/PlantCritter_TransitionTable.asset
Labels: enhancement

#299 Added Critter SO - Item drop when killed - FR critter names
  UOP1_Project/Assets/AddressableAssetsData/AssetGroups/Localization-Assets-Shared.asset
  UOP1_Project/Assets/AddressableAssetsData/AssetGroups/Localization-StringTables.asset
  UOP1_Project/Assets/Localization Files/Asset Tables/Critters.meta
  UOP1_Project/Assets/Localization Files/Asset Tables/Critters/Critters Shared Data.asset
  UOP1_Project/Assets/Localization Files/Asset Tables/Critters/Critters Shared Data.asset.meta
  UOP1_Project/Assets/Localization Files/Asset Tables/Critters/Critters.asset
  UOP1_Project/Assets/Localization Files/Asset Tables/Critters/Critters.asset.meta
  UOP1_Project/Assets/Localization Files/Asset Tables/Critters/Critters_en.asset
  UOP1_Project/Assets/Localization Files/Asset Tables/Critters/Critters_en.asset.meta
  UOP1_Project/Assets/Localization Files/Asset Tables/Critters/Critters_fr.asset
  UOP1_Project/Assets/Localization Files/Asset Tables/Critters/Critters_fr.asset.meta
  UOP1_Project/Assets/Prefabs/Characters/PlantCritter.prefab
  UOP1_Project/Assets/Prefabs/Props/Collectible Item.prefab
  UOP1_Project/Assets/ScriptableObjects/Critters.meta
  UOP1_Project/Assets/ScriptableObjects/Critters/PlantCritter.asset
  UOP1_Project/Assets/ScriptableObjects/Critters/PlantCritter.asset.meta
  UOP1_Project/Assets/Scripts/Characters/Critter.cs
  UOP1_Project/Assets/Scripts/Characters/DropItem.cs
  UOP1_Project/Assets/Scripts/Characters/DropItem.cs.meta
  UOP1_Project/Assets/Scripts/Characters/ScriptableObjects.meta
  UOP1_Project/Assets/Scripts/Characters/ScriptableObjects/CritterSO.cs
  UOP1_Project/Assets/Scripts/Characters/ScriptableObjects/CritterSO.cs.meta
  UOP1_Project/Assets/Scripts/Characters/StateMachine/Actions/DestroyCritterSO.cs
  UOP1_Project/Assets/Scripts/Inventory/CollectibleItem.cs
Labels: enhancement

#315 Slime critter propelling attack movement
  UOP1_Project/Assets/Art/Characters/SlimeCritter/Animation/Attack.anim
  UOP1_Project/Assets/Art/Characters/SlimeCritter/Animation/Attack.anim.meta
  UOP1_Project/Assets/Art/Characters/SlimeCritter/Animation/SlimeCritter.controller
  UOP1_Project/Assets/Prefabs/Characters/SlimeCritter_Base.prefab
  UOP1_Project/Assets/ProBuilder Data.meta
  UOP1_Project/Assets/Scripts/Characters/SlimeCritterAttackController.cs
  UOP1_Project/Assets/Scripts/Characters/SlimeCritterAttackController.cs.meta
Labels: enhancement

#282 Added new Accessory: Unibrow
  UOP1_Project/Assets/Art/Accessories/Unibrow.meta
  UOP1_Project/Assets/Art/Accessories/Unibrow/Unibrow.fbx
  UOP1_Project/Assets/Art/Accessories/Unibrow/Unibrow.fbx.meta
  UOP1_Project/Assets/Prefabs/Accessories/Unibrow.prefab
  UOP1_Project/Assets/Prefabs/Accessories/Unibrow.prefab.meta
Labels: art

#320 Created a Farmer Hat for Accessories(Art Asset)
  UOP1_Project/Assets/Art/Accessories/FarmersHat.meta
  UOP1_Project/Assets/Art/Accessories/FarmersHat/FarmerHat_001Texture.jpg
  UOP1_Project/Assets/Art/Accessories/FarmersHat/FarmerHat_001Texture.jpg.meta
  UOP1_Project/Assets/Art/Accessories/FarmersHat/FarmerHat_001Texture.mat
  UOP1_Project/Assets/Art/Accessories/FarmersHat/FarmerHat_001Texture.mat.meta
  UOP1_Project/Assets/Art/Accessories/FarmersHat/FarmersHat_Mesh.fbx
  UOP1_Project/Assets/Art/Accessories/FarmersHat/FarmersHat_Mesh.fbx.meta
  UOP1_Project/Assets/Prefabs/Accessories/FarmersHat.prefab
  UOP1_Project/Assets/Prefabs/Accessories/FarmersHat.prefab.meta
Labels: art

#314 State Machine Improvements
  UOP1_Project/Assets/Scripts/StateMachine/Core/StateAction.cs
  UOP1_Project/Assets/Scripts/StateMachine/Core/StateCondition.cs
  UOP1_Project/Assets/Scripts/StateMachine/Core/StateMachine.cs
  UOP1_Project/Assets/Scripts/StateMachine/Editor/Templates/StateAction.txt
  UOP1_Project/Assets/Scripts/StateMachine/Editor/Templates/StateCondition.txt
  UOP1_Project/Assets/Scripts/StateMachine/Editor/TransitionTableEditor.cs
  UOP1_Project/Assets/Scripts/StateMachine/Editor/TransitionTableEditorWindow.cs
  UOP1_Project/Assets/Scripts/StateMachine/Editor/Utilities/AddTransitionHelper.cs
  UOP1_Project/Assets/Scripts/StateMachine/Editor/Utilities/ContentStyle.cs
  UOP1_Project/Assets/Scripts/StateMachine/Editor/Utilities/TransitionDisplayHelper.cs
Labels: enhancement

#316 Added AA, Distance Fading and Screen Resolution independency to Outline
  UOP1_Project/Assets/Shaders/SubGraphs/Outline.shadersubgraph
Labels: art

#317 Fix for issue #206: Objects are black when the scene is not baked
  UOP1_Project/Assets/Shaders/SubGraphs/ToonLightingModel.shadersubgraph
Labels: art

#301 Added support to multiple overlapping interactions
  UOP1_Project/Assets/Scripts/Interaction/Interaction.cs
  UOP1_Project/Assets/Scripts/Interaction/Interaction.cs.meta
  UOP1_Project/Assets/Scripts/Interaction/InteractionManager.cs
Labels: enhancement

#336 Add a Stop and Finish option for the AudioManager
  UOP1_Project/Assets/Scripts/Audio/AudioCue.cs
  UOP1_Project/Assets/Scripts/Audio/AudioData/AudioCueKey.cs
  UOP1_Project/Assets/Scripts/Audio/AudioData/AudioCueKey.cs.meta
  UOP1_Project/Assets/Scripts/Audio/AudioManager.cs
  UOP1_Project/Assets/Scripts/Audio/SoundEmitters/SoundEmitter.cs
  UOP1_Project/Assets/Scripts/Audio/SoundEmitters/SoundEmitterList.cs
  UOP1_Project/Assets/Scripts/Audio/SoundEmitters/SoundEmitterList.cs.meta
  UOP1_Project/Assets/Scripts/Characters/ProtagonistAudio.cs
  UOP1_Project/Assets/Scripts/Characters/StateMachine/Actions/PlayAudioCueActionSO.cs
  UOP1_Project/Assets/Scripts/Events/ScriptableObjects/AudioCueEventChannelSO.cs
Labels: enhancement
