Repository UnityTechnologies/open-project-1, pull requests merged in 2021-07, with the labels that each got.

#467 fix: add null check
  UOP1_Project/Assets/Scripts/Events/ScriptableObjects/IntEventChannelSO.cs
Labels: enhancement

#464 Fixed landing particles playing in air when attacking bug
  UOP1_Project/Assets/Scripts/Characters/StateMachine/Actions/PlayLandParticlesActionSO.cs
Labels: bug (minor)

#463 Implement pause menu music
  UOP1_Project/Assets/Prefabs/Gameplay/MusicPlayer.prefab
  UOP1_Project/Assets/Prefabs/UI/GameplayScene/Pause_Screen.prefab
  UOP1_Project/Assets/ScriptableObjects/UI/OnPauseOpened.asset
  UOP1_Project/Assets/ScriptableObjects/UI/OnPauseOpened.asset.meta
  UOP1_Project/Assets/Scripts/Audio/MusicPlayer.cs
  UOP1_Project/Assets/Scripts/UI/UIPause.cs
Labels: enhancement

#474 Modifying Railed Bridge Meshes(Changing Mesh and Colliders)
  UOP1_Project/Assets/Art/Props/Railed_Bridges/Railed_Long_Bridge/Railed_Long_Bridge_Collider.fbx
  UOP1_Project/Assets/Art/Props/Railed_Bridges/Railed_Long_Bridge/Railed_Long_Bridge_LongBeams_Mesh.meta
  UOP1_Project/Assets/Art/Props/Railed_Bridges/Railed_Long_Bridge/Railed_Long_Bridge_LongBeams_Mesh/Railed_Long_Bridge_LongBeams_Collider.fbx
  UOP1_Project/Assets/Art/Props/Railed_Bridges/Railed_Long_Bridge/Railed_Long_Bridge_LongBeams_Mesh/Railed_Long_Bridge_LongBeams_Collider.fbx.meta
  UOP1_Project/Assets/Art/Props/Railed_Bridges/Railed_Long_Bridge/Railed_Long_Bridge_LongBeams_Mesh/Railed_Long_Bridge_LongBeams_Material.mat
  UOP1_Project/Assets/Art/Props/Railed_Bridges/Railed_Long_Bridge/Railed_Long_Bridge_LongBeams_Mesh/Railed_Long_Bridge_LongBeams_Material.mat.meta
  UOP1_Project/Assets/Art/Props/Railed_Bridges/Railed_Long_Bridge/Railed_Long_Bridge_LongBeams_Mesh/Railed_Long_Bridge_LongBeams_Mesh.fbx
  UOP1_Project/Assets/Art/Props/Railed_Bridges/Railed_Long_Bridge/Railed_Long_Bridge_LongBeams_Mesh/Railed_Long_Bridge_LongBeams_Mesh.fbx.meta
  UOP1_Project/Assets/Art/Props/Railed_Bridges/Railed_Long_Bridge/Railed_Long_Bridge_LongBeams_Mesh/Railed_Long_Bridge_LongBeams_Texture.png
  UOP1_Project/Assets/Art/Props/Railed_Bridges/Railed_Long_Bridge/Railed_Long_Bridge_LongBeams_Mesh/Railed_Long_Bridge_LongBeams_Texture.png.meta
  UOP1_Project/Assets/Art/Props/Railed_Bridges/Railed_Long_Bridge/Railed_Long_Bridge_Mesh.fbx
  UOP1_Project/Assets/Art/Props/Railed_Bridges/Railed_Long_Bridge/Railed_Long_Bridge_NoBeams_Mesh.meta
  UOP1_Project/Assets/Art/Props/Railed_Bridges/Railed_Long_Bridge/Railed_Long_Bridge_NoBeams_Mesh/Railed_Long_Bride_NoBeams_Texture.png
  UOP1_Project/Assets/Art/Props/Railed_Bridges/Railed_Long_Bridge/Railed_Long_Bridge_NoBeams_Mesh/Railed_Long_Bride_NoBeams_Texture.png.meta
  UOP1_Project/Assets/Art/Props/Railed_Bridges/Railed_Long_Bridge/Railed_Long_Bridge_NoBeams_Mesh/Railed_Long_Bridge_NoBeams_Collider.fbx
  UOP1_Project/Assets/Art/Props/Railed_Bridges/Railed_Long_Bridge/Railed_Long_Bridge_NoBeams_Mesh/Railed_Long_Bridge_NoBeams_Collider.fbx.meta
  UOP1_Project/Assets/Art/Props/Railed_Bridges/Railed_Long_Bridge/Railed_Long_Bridge_NoBeams_Mesh/Railed_Long_Bridge_NoBeams_Material.mat
  UOP1_Project/Assets/Art/Props/Railed_Bridges/Railed_Long_Bridge/Railed_Long_Bridge_NoBeams_Mesh/Railed_Long_Bridge_NoBeams_Material.mat.meta
  UOP1_Project/Assets/Art/Props/Railed_Bridges/Railed_Long_Bridge/Railed_Long_Bridge_NoBeams_Mesh/Railed_Long_Bridge_NoBeams_Mesh.fbx
  UOP1_Project/Assets/Art/Props/Railed_Bridges/Railed_Long_Bridge/Railed_Long_Bridge_NoBeams_Mesh/Railed_Long_Bridge_NoBeams_Mesh.fbx.meta
  UOP1_Project/Assets/Prefabs/TownStructures/Railed_Bridge_Long_NoBeam_Prefab.prefab
  UOP1_Project/Assets/Prefabs/TownStructures/Railed_Bridge_Long_NoBeam_Prefab.prefab.meta
  UOP1_Project/Assets/Prefabs/TownStructures/Railed_Long_Bridge_LongBeam_Prefab.prefab
  UOP1_Project/Assets/Prefabs/TownStructures/Railed_Long_Bridge_LongBeam_Prefab.prefab.meta
Labels: art

#400 fix: checking if the old save file exists
  UOP1_Project/Assets/Scripts/SaveSystem/FileManager.cs
Labels: bug (minor)
